export default {
  COMMENT: 'comment',
  DIARY_LIST: 'diaryList',
  DIARY_DETAIL: 'diaryDetail',
  TRADE_LIST: 'tradeList',
  TRADE_DETAIL: 'tradeDetail',
  COMMUNITY_LIST_TOTAL: 'communityListTotal',
  COMMUNITY_LIST_LOCAL: 'communityListLocal',
  COMMUNITY_DETAIL: 'communityDetail',
  COMMUNITY_LIKE: 'communityLike',
  COMMUNITY_WRITTEN_BY_USER: 'communityWrittenByUser',
  PROFILE: 'profile',
  NEIGHBOR_CROP_LIST: 'neighborCropList',
  TRADE_PICKED_BY_USER: 'tradePickedByUser',
  TRADE_WRITTEN_BY_USER: 'tradeWrittenByUser',
  CROP_CATEGORY: 'cropCategory',
  CROP_PROFILE: 'cropProfile',
  AI_REPORT_LIST: 'aiReportList',
  AI_REPORT_DETAIL: 'aiReportDetail',
  DIARY_AI_REPORT: 'diaryAiReport',
  SEARCH: 'search',
};