export default {
  COMMENT: 'comment',
  HAS_DIARY: 'hasDiary',
  DIARY_LIST: 'diaryList',
  DIARY_DETAIL: 'diaryDetail',
  TRADE_LIST: 'tradeList',
  TRADE_DETAIL: 'tradeDetail',
  COMMUNITY_LIST: 'communityList',
  // COMMUNITY_LIST_LOCAL: 'communityListLocal',
  COMMUNITY_DETAIL: 'communityDetail',
  COMMUNITY_LIKE: 'communityLike',
  COMMUNITY_WRITTEN_BY_USER: 'communityWrittenByUser',
  PROFILE: 'profile',
  PROFILE_LIST: 'profileList',
  NEIGHBOR_CROP_LIST: 'neighborCropList',
  TRADE_PICKED_BY_USER: 'tradePickedByUser',
  TRADE_WRITTEN_BY_USER: 'tradeWrittenByUser',
  CROP_CATEGORY: 'cropCategory',
  CROP_PROFILE: 'cropProfile',
  AI_REPORT_LIST: 'aiReportList',
  AI_REPORT_DETAIL: 'aiReportDetail',
  DAILY_TIP: 'dailyTip',
  SEARCH: 'search',
  SEARCH_RECENT:'searchRecent',
  SEARCH_SUGGESTION:'searchSuggestion',
  LOCATION: 'location',
};