/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSignupIndexImport } from './routes/_layout/signup/index'
import { Route as LayoutSearchIndexImport } from './routes/_layout/search/index'
import { Route as LayoutLoginIndexImport } from './routes/_layout/login/index'
import { Route as LayoutHomeIndexImport } from './routes/_layout/home/index'
import { Route as LayoutDiaryIndexImport } from './routes/_layout/diary/index'
import { Route as LayoutCommunityIndexImport } from './routes/_layout/community/index'
import { Route as LayoutSignupLayoutImport } from './routes/_layout/signup/_layout'
import { Route as LayoutDiaryMyCropsImport } from './routes/_layout/diary/myCrops'
import { Route as LayoutDiaryCalendarImport } from './routes/_layout/diary/calendar'
import { Route as LayoutCommunityCreateImport } from './routes/_layout/community/create'
import { Route as LayoutLoginEntranceIndexImport } from './routes/_layout/login/entrance/index'
import { Route as LayoutSignupLayout9Import } from './routes/_layout/signup/_layout/9'
import { Route as LayoutSignupLayout8Import } from './routes/_layout/signup/_layout/8'
import { Route as LayoutSignupLayout7Import } from './routes/_layout/signup/_layout/7'
import { Route as LayoutSignupLayout6Import } from './routes/_layout/signup/_layout/6'
import { Route as LayoutSignupLayout5Import } from './routes/_layout/signup/_layout/5'
import { Route as LayoutSignupLayout4Import } from './routes/_layout/signup/_layout/4'
import { Route as LayoutSignupLayout3Import } from './routes/_layout/signup/_layout/3'
import { Route as LayoutSignupLayout2Import } from './routes/_layout/signup/_layout/2'
import { Route as LayoutSignupLayout1Import } from './routes/_layout/signup/_layout/1'
import { Route as LayoutDiaryWriteDiaryWriteCropDiaryImport } from './routes/_layout/diary/writeDiary/writeCropDiary'
import { Route as LayoutDiaryWriteDiarySelectCropImport } from './routes/_layout/diary/writeDiary/selectCrop'
import { Route as LayoutDiaryWriteDiaryDetailCropDiaryImport } from './routes/_layout/diary/writeDiary/detailCropDiary'
import { Route as LayoutDiaryCreateCropNicknameImport } from './routes/_layout/diary/createCrop/nickname'
import { Route as LayoutDiaryCreateCropIntroduceImport } from './routes/_layout/diary/createCrop/introduce'
import { Route as LayoutDiaryCreateCropCropProfileImport } from './routes/_layout/diary/createCrop/cropProfile'
import { Route as LayoutDiaryCreateCropCropImageImport } from './routes/_layout/diary/createCrop/cropImage'
import { Route as LayoutCommunityDetailPostIdImport } from './routes/_layout/community/detail/$postId'

// Create Virtual Routes

const LayoutSignupImport = createFileRoute('/_layout/signup')()

// Create/Update Routes

const TestRoute = TestImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSignupRoute = LayoutSignupImport.update({
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSignupIndexRoute = LayoutSignupIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutSignupRoute,
} as any)

const LayoutSearchIndexRoute = LayoutSearchIndexImport.update({
  path: '/search/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginIndexRoute = LayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeIndexRoute = LayoutHomeIndexImport.update({
  path: '/home/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDiaryIndexRoute = LayoutDiaryIndexImport.update({
  path: '/diary/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCommunityIndexRoute = LayoutCommunityIndexImport.update({
  path: '/community/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSignupLayoutRoute = LayoutSignupLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutSignupRoute,
} as any)

const LayoutDiaryMyCropsRoute = LayoutDiaryMyCropsImport.update({
  path: '/diary/myCrops',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDiaryCalendarRoute = LayoutDiaryCalendarImport.update({
  path: '/diary/calendar',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCommunityCreateRoute = LayoutCommunityCreateImport.update({
  path: '/community/create',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginEntranceIndexRoute = LayoutLoginEntranceIndexImport.update({
  path: '/login/entrance/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSignupLayout9Route = LayoutSignupLayout9Import.update({
  path: '/9',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout8Route = LayoutSignupLayout8Import.update({
  path: '/8',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout7Route = LayoutSignupLayout7Import.update({
  path: '/7',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout6Route = LayoutSignupLayout6Import.update({
  path: '/6',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout5Route = LayoutSignupLayout5Import.update({
  path: '/5',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout4Route = LayoutSignupLayout4Import.update({
  path: '/4',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout3Route = LayoutSignupLayout3Import.update({
  path: '/3',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout2Route = LayoutSignupLayout2Import.update({
  path: '/2',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout1Route = LayoutSignupLayout1Import.update({
  path: '/1',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutDiaryWriteDiaryWriteCropDiaryRoute =
  LayoutDiaryWriteDiaryWriteCropDiaryImport.update({
    path: '/diary/writeDiary/writeCropDiary',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDiaryWriteDiarySelectCropRoute =
  LayoutDiaryWriteDiarySelectCropImport.update({
    path: '/diary/writeDiary/selectCrop',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDiaryWriteDiaryDetailCropDiaryRoute =
  LayoutDiaryWriteDiaryDetailCropDiaryImport.update({
    path: '/diary/writeDiary/detailCropDiary',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDiaryCreateCropNicknameRoute =
  LayoutDiaryCreateCropNicknameImport.update({
    path: '/diary/createCrop/nickname',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDiaryCreateCropIntroduceRoute =
  LayoutDiaryCreateCropIntroduceImport.update({
    path: '/diary/createCrop/introduce',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDiaryCreateCropCropProfileRoute =
  LayoutDiaryCreateCropCropProfileImport.update({
    path: '/diary/createCrop/cropProfile',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDiaryCreateCropCropImageRoute =
  LayoutDiaryCreateCropCropImageImport.update({
    path: '/diary/createCrop/cropImage',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutCommunityDetailPostIdRoute =
  LayoutCommunityDetailPostIdImport.update({
    path: '/community/detail/$postId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/community/create': {
      id: '/_layout/community/create'
      path: '/community/create'
      fullPath: '/community/create'
      preLoaderRoute: typeof LayoutCommunityCreateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/calendar': {
      id: '/_layout/diary/calendar'
      path: '/diary/calendar'
      fullPath: '/diary/calendar'
      preLoaderRoute: typeof LayoutDiaryCalendarImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/myCrops': {
      id: '/_layout/diary/myCrops'
      path: '/diary/myCrops'
      fullPath: '/diary/myCrops'
      preLoaderRoute: typeof LayoutDiaryMyCropsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup': {
      id: '/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/_layout': {
      id: '/_layout/signup/_layout'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupLayoutImport
      parentRoute: typeof LayoutSignupRoute
    }
    '/_layout/community/': {
      id: '/_layout/community/'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof LayoutCommunityIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/': {
      id: '/_layout/diary/'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof LayoutDiaryIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/': {
      id: '/_layout/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/login/': {
      id: '/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/': {
      id: '/_layout/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/': {
      id: '/_layout/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof LayoutSignupIndexImport
      parentRoute: typeof LayoutSignupImport
    }
    '/_layout/community/detail/$postId': {
      id: '/_layout/community/detail/$postId'
      path: '/community/detail/$postId'
      fullPath: '/community/detail/$postId'
      preLoaderRoute: typeof LayoutCommunityDetailPostIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/createCrop/cropImage': {
      id: '/_layout/diary/createCrop/cropImage'
      path: '/diary/createCrop/cropImage'
      fullPath: '/diary/createCrop/cropImage'
      preLoaderRoute: typeof LayoutDiaryCreateCropCropImageImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/createCrop/cropProfile': {
      id: '/_layout/diary/createCrop/cropProfile'
      path: '/diary/createCrop/cropProfile'
      fullPath: '/diary/createCrop/cropProfile'
      preLoaderRoute: typeof LayoutDiaryCreateCropCropProfileImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/createCrop/introduce': {
      id: '/_layout/diary/createCrop/introduce'
      path: '/diary/createCrop/introduce'
      fullPath: '/diary/createCrop/introduce'
      preLoaderRoute: typeof LayoutDiaryCreateCropIntroduceImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/createCrop/nickname': {
      id: '/_layout/diary/createCrop/nickname'
      path: '/diary/createCrop/nickname'
      fullPath: '/diary/createCrop/nickname'
      preLoaderRoute: typeof LayoutDiaryCreateCropNicknameImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/writeDiary/detailCropDiary': {
      id: '/_layout/diary/writeDiary/detailCropDiary'
      path: '/diary/writeDiary/detailCropDiary'
      fullPath: '/diary/writeDiary/detailCropDiary'
      preLoaderRoute: typeof LayoutDiaryWriteDiaryDetailCropDiaryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/writeDiary/selectCrop': {
      id: '/_layout/diary/writeDiary/selectCrop'
      path: '/diary/writeDiary/selectCrop'
      fullPath: '/diary/writeDiary/selectCrop'
      preLoaderRoute: typeof LayoutDiaryWriteDiarySelectCropImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/writeDiary/writeCropDiary': {
      id: '/_layout/diary/writeDiary/writeCropDiary'
      path: '/diary/writeDiary/writeCropDiary'
      fullPath: '/diary/writeDiary/writeCropDiary'
      preLoaderRoute: typeof LayoutDiaryWriteDiaryWriteCropDiaryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/_layout/1': {
      id: '/_layout/signup/_layout/1'
      path: '/1'
      fullPath: '/signup/1'
      preLoaderRoute: typeof LayoutSignupLayout1Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/2': {
      id: '/_layout/signup/_layout/2'
      path: '/2'
      fullPath: '/signup/2'
      preLoaderRoute: typeof LayoutSignupLayout2Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/3': {
      id: '/_layout/signup/_layout/3'
      path: '/3'
      fullPath: '/signup/3'
      preLoaderRoute: typeof LayoutSignupLayout3Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/4': {
      id: '/_layout/signup/_layout/4'
      path: '/4'
      fullPath: '/signup/4'
      preLoaderRoute: typeof LayoutSignupLayout4Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/5': {
      id: '/_layout/signup/_layout/5'
      path: '/5'
      fullPath: '/signup/5'
      preLoaderRoute: typeof LayoutSignupLayout5Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/6': {
      id: '/_layout/signup/_layout/6'
      path: '/6'
      fullPath: '/signup/6'
      preLoaderRoute: typeof LayoutSignupLayout6Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/7': {
      id: '/_layout/signup/_layout/7'
      path: '/7'
      fullPath: '/signup/7'
      preLoaderRoute: typeof LayoutSignupLayout7Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/8': {
      id: '/_layout/signup/_layout/8'
      path: '/8'
      fullPath: '/signup/8'
      preLoaderRoute: typeof LayoutSignupLayout8Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/9': {
      id: '/_layout/signup/_layout/9'
      path: '/9'
      fullPath: '/signup/9'
      preLoaderRoute: typeof LayoutSignupLayout9Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/login/entrance/': {
      id: '/_layout/login/entrance/'
      path: '/login/entrance'
      fullPath: '/login/entrance'
      preLoaderRoute: typeof LayoutLoginEntranceIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutIndexRoute,
    LayoutCommunityCreateRoute,
    LayoutDiaryCalendarRoute,
    LayoutDiaryMyCropsRoute,
    LayoutSignupRoute: LayoutSignupRoute.addChildren({
      LayoutSignupLayoutRoute: LayoutSignupLayoutRoute.addChildren({
        LayoutSignupLayout1Route,
        LayoutSignupLayout2Route,
        LayoutSignupLayout3Route,
        LayoutSignupLayout4Route,
        LayoutSignupLayout5Route,
        LayoutSignupLayout6Route,
        LayoutSignupLayout7Route,
        LayoutSignupLayout8Route,
        LayoutSignupLayout9Route,
      }),
      LayoutSignupIndexRoute,
    }),
    LayoutCommunityIndexRoute,
    LayoutDiaryIndexRoute,
    LayoutHomeIndexRoute,
    LayoutLoginIndexRoute,
    LayoutSearchIndexRoute,
    LayoutCommunityDetailPostIdRoute,
    LayoutDiaryCreateCropCropImageRoute,
    LayoutDiaryCreateCropCropProfileRoute,
    LayoutDiaryCreateCropIntroduceRoute,
    LayoutDiaryCreateCropNicknameRoute,
    LayoutDiaryWriteDiaryDetailCropDiaryRoute,
    LayoutDiaryWriteDiarySelectCropRoute,
    LayoutDiaryWriteDiaryWriteCropDiaryRoute,
    LayoutLoginEntranceIndexRoute,
  }),
  TestRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/test"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/community/create",
        "/_layout/diary/calendar",
        "/_layout/diary/myCrops",
        "/_layout/signup",
        "/_layout/community/",
        "/_layout/diary/",
        "/_layout/home/",
        "/_layout/login/",
        "/_layout/search/",
        "/_layout/community/detail/$postId",
        "/_layout/diary/createCrop/cropImage",
        "/_layout/diary/createCrop/cropProfile",
        "/_layout/diary/createCrop/introduce",
        "/_layout/diary/createCrop/nickname",
        "/_layout/diary/writeDiary/detailCropDiary",
        "/_layout/diary/writeDiary/selectCrop",
        "/_layout/diary/writeDiary/writeCropDiary",
        "/_layout/login/entrance/"
      ]
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/community/create": {
      "filePath": "_layout/community/create.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/calendar": {
      "filePath": "_layout/diary/calendar.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/myCrops": {
      "filePath": "_layout/diary/myCrops.tsx",
      "parent": "/_layout"
    },
    "/_layout/signup": {
      "filePath": "_layout/signup",
      "parent": "/_layout",
      "children": [
        "/_layout/signup/_layout",
        "/_layout/signup/"
      ]
    },
    "/_layout/signup/_layout": {
      "filePath": "_layout/signup/_layout.tsx",
      "parent": "/_layout/signup",
      "children": [
        "/_layout/signup/_layout/1",
        "/_layout/signup/_layout/2",
        "/_layout/signup/_layout/3",
        "/_layout/signup/_layout/4",
        "/_layout/signup/_layout/5",
        "/_layout/signup/_layout/6",
        "/_layout/signup/_layout/7",
        "/_layout/signup/_layout/8",
        "/_layout/signup/_layout/9"
      ]
    },
    "/_layout/community/": {
      "filePath": "_layout/community/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/": {
      "filePath": "_layout/diary/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/home/": {
      "filePath": "_layout/home/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/login/": {
      "filePath": "_layout/login/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/search/": {
      "filePath": "_layout/search/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/signup/": {
      "filePath": "_layout/signup/index.tsx",
      "parent": "/_layout/signup"
    },
    "/_layout/community/detail/$postId": {
      "filePath": "_layout/community/detail/$postId.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/createCrop/cropImage": {
      "filePath": "_layout/diary/createCrop/cropImage.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/createCrop/cropProfile": {
      "filePath": "_layout/diary/createCrop/cropProfile.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/createCrop/introduce": {
      "filePath": "_layout/diary/createCrop/introduce.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/createCrop/nickname": {
      "filePath": "_layout/diary/createCrop/nickname.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/writeDiary/detailCropDiary": {
      "filePath": "_layout/diary/writeDiary/detailCropDiary.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/writeDiary/selectCrop": {
      "filePath": "_layout/diary/writeDiary/selectCrop.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/writeDiary/writeCropDiary": {
      "filePath": "_layout/diary/writeDiary/writeCropDiary.tsx",
      "parent": "/_layout"
    },
    "/_layout/signup/_layout/1": {
      "filePath": "_layout/signup/_layout/1.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/2": {
      "filePath": "_layout/signup/_layout/2.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/3": {
      "filePath": "_layout/signup/_layout/3.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/4": {
      "filePath": "_layout/signup/_layout/4.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/5": {
      "filePath": "_layout/signup/_layout/5.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/6": {
      "filePath": "_layout/signup/_layout/6.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/7": {
      "filePath": "_layout/signup/_layout/7.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/8": {
      "filePath": "_layout/signup/_layout/8.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/9": {
      "filePath": "_layout/signup/_layout/9.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/login/entrance/": {
      "filePath": "_layout/login/entrance/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
