/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutSignupIndexImport } from './routes/_layout/signup/index'
import { Route as LayoutSearchIndexImport } from './routes/_layout/search/index'
import { Route as LayoutLoginIndexImport } from './routes/_layout/login/index'
import { Route as LayoutDiaryIndexImport } from './routes/_layout/diary/index'
import { Route as LayoutTradeLayoutImport } from './routes/_layout/trade/_layout'
import { Route as LayoutSignupLayoutImport } from './routes/_layout/signup/_layout'
import { Route as LayoutProfileLayoutImport } from './routes/_layout/profile/_layout'
import { Route as LayoutHomeLayoutImport } from './routes/_layout/home/_layout'
import { Route as LayoutCommunityLayoutImport } from './routes/_layout/community/_layout'
import { Route as LayoutTradeLayoutIndexImport } from './routes/_layout/trade/_layout/index'
import { Route as LayoutProfileAireportIndexImport } from './routes/_layout/profile/aireport/index'
import { Route as LayoutProfileLayoutIndexImport } from './routes/_layout/profile/_layout/index'
import { Route as LayoutLoginEntranceIndexImport } from './routes/_layout/login/entrance/index'
import { Route as LayoutHomeLayoutIndexImport } from './routes/_layout/home/_layout/index'
import { Route as LayoutDiaryWriteIndexImport } from './routes/_layout/diary/write/index'
import { Route as LayoutDiaryRegisterCropIndexImport } from './routes/_layout/diary/registerCrop/index'
import { Route as LayoutCommunityCreateIndexImport } from './routes/_layout/community/create/index'
import { Route as LayoutCommunityLayoutIndexImport } from './routes/_layout/community/_layout/index'
import { Route as LayoutTradeWriteLayoutImport } from './routes/_layout/trade/write/_layout'
import { Route as LayoutTradeToLayoutImport } from './routes/_layout/trade/to/_layout'
import { Route as LayoutTradeFromLayoutImport } from './routes/_layout/trade/from/_layout'
import { Route as LayoutTradeDetailLayoutImport } from './routes/_layout/trade/detail/_layout'
import { Route as LayoutSignupLayout9Import } from './routes/_layout/signup/_layout/9'
import { Route as LayoutSignupLayout8Import } from './routes/_layout/signup/_layout/8'
import { Route as LayoutSignupLayout7Import } from './routes/_layout/signup/_layout/7'
import { Route as LayoutSignupLayout6Import } from './routes/_layout/signup/_layout/6'
import { Route as LayoutSignupLayout5Import } from './routes/_layout/signup/_layout/5'
import { Route as LayoutSignupLayout4Import } from './routes/_layout/signup/_layout/4'
import { Route as LayoutSignupLayout3Import } from './routes/_layout/signup/_layout/3'
import { Route as LayoutSignupLayout2Import } from './routes/_layout/signup/_layout/2'
import { Route as LayoutSignupLayout1Import } from './routes/_layout/signup/_layout/1'
import { Route as LayoutSearchResultLayoutImport } from './routes/_layout/search/$result/_layout'
import { Route as LayoutProfileWritedLayoutImport } from './routes/_layout/profile/writed/_layout'
import { Route as LayoutProfilePickedLayoutImport } from './routes/_layout/profile/picked/_layout'
import { Route as LayoutProfileChatLayoutImport } from './routes/_layout/profile/chat/_layout'
import { Route as LayoutProfileChangelocationLayoutImport } from './routes/_layout/profile/changelocation/_layout'
import { Route as LayoutDiaryWriteLayoutImport } from './routes/_layout/diary/write/_layout'
import { Route as LayoutDiaryRegisterCropLayoutImport } from './routes/_layout/diary/registerCrop/_layout'
import { Route as LayoutDiaryGrowDiaryCropIdImport } from './routes/_layout/diary/growDiary/$cropId'
import { Route as LayoutDiaryDetailDiaryIdImport } from './routes/_layout/diary/detail/$diaryId'
import { Route as LayoutCommunityDetailLayoutImport } from './routes/_layout/community/detail/_layout'
import { Route as LayoutTradeWriteLayoutIndexImport } from './routes/_layout/trade/write/_layout/index'
import { Route as LayoutTradeToLayoutIndexImport } from './routes/_layout/trade/to/_layout/index'
import { Route as LayoutTradeFromLayoutIndexImport } from './routes/_layout/trade/from/_layout/index'
import { Route as LayoutSearchResultLayoutIndexImport } from './routes/_layout/search/$result/_layout/index'
import { Route as LayoutProfileWritedLayoutIndexImport } from './routes/_layout/profile/writed/_layout/index'
import { Route as LayoutProfilePickedLayoutIndexImport } from './routes/_layout/profile/picked/_layout/index'
import { Route as LayoutProfileChatLayoutIndexImport } from './routes/_layout/profile/chat/_layout/index'
import { Route as LayoutProfileChangelocationLayoutIndexImport } from './routes/_layout/profile/changelocation/_layout/index'
import { Route as LayoutTradeDetailLayoutTradeIdImport } from './routes/_layout/trade/detail/_layout/$tradeId'
import { Route as LayoutProfileAireportDetailReportIdImport } from './routes/_layout/profile/aireport/detail/$reportId'
import { Route as LayoutProfileNicknameDiaryLayoutImport } from './routes/_layout/profile/$nickname/diary/_layout'
import { Route as LayoutProfileNicknameCropStorageLayoutImport } from './routes/_layout/profile/$nickname/cropStorage/_layout'
import { Route as LayoutDiaryWriteLayout2Import } from './routes/_layout/diary/write/_layout/2'
import { Route as LayoutDiaryWriteLayout1Import } from './routes/_layout/diary/write/_layout/1'
import { Route as LayoutDiaryRegisterCropLayout5Import } from './routes/_layout/diary/registerCrop/_layout/5'
import { Route as LayoutDiaryRegisterCropLayout4Import } from './routes/_layout/diary/registerCrop/_layout/4'
import { Route as LayoutDiaryRegisterCropLayout3Import } from './routes/_layout/diary/registerCrop/_layout/3'
import { Route as LayoutDiaryRegisterCropLayout2Import } from './routes/_layout/diary/registerCrop/_layout/2'
import { Route as LayoutDiaryRegisterCropLayout1Import } from './routes/_layout/diary/registerCrop/_layout/1'
import { Route as LayoutCommunityDetailLayoutPostIdImport } from './routes/_layout/community/detail/_layout/$postId'
import { Route as LayoutProfileNicknameDiaryLayoutIndexImport } from './routes/_layout/profile/$nickname/diary/_layout/index'
import { Route as LayoutProfileNicknameCropStorageLayoutIndexImport } from './routes/_layout/profile/$nickname/cropStorage/_layout/index'

// Create Virtual Routes

const LayoutTradeImport = createFileRoute('/_layout/trade')()
const LayoutSignupImport = createFileRoute('/_layout/signup')()
const LayoutProfileImport = createFileRoute('/_layout/profile')()
const LayoutHomeImport = createFileRoute('/_layout/home')()
const LayoutCommunityImport = createFileRoute('/_layout/community')()
const LayoutTradeWriteImport = createFileRoute('/_layout/trade/write')()
const LayoutTradeToImport = createFileRoute('/_layout/trade/to')()
const LayoutTradeFromImport = createFileRoute('/_layout/trade/from')()
const LayoutTradeDetailImport = createFileRoute('/_layout/trade/detail')()
const LayoutSearchResultImport = createFileRoute('/_layout/search/$result')()
const LayoutProfileWritedImport = createFileRoute('/_layout/profile/writed')()
const LayoutProfilePickedImport = createFileRoute('/_layout/profile/picked')()
const LayoutProfileChatImport = createFileRoute('/_layout/profile/chat')()
const LayoutProfileChangelocationImport = createFileRoute(
  '/_layout/profile/changelocation',
)()
const LayoutDiaryWriteImport = createFileRoute('/_layout/diary/write')()
const LayoutDiaryRegisterCropImport = createFileRoute(
  '/_layout/diary/registerCrop',
)()
const LayoutCommunityDetailImport = createFileRoute(
  '/_layout/community/detail',
)()
const LayoutProfileNicknameDiaryImport = createFileRoute(
  '/_layout/profile/$nickname/diary',
)()
const LayoutProfileNicknameCropStorageImport = createFileRoute(
  '/_layout/profile/$nickname/cropStorage',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutTradeRoute = LayoutTradeImport.update({
  path: '/trade',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSignupRoute = LayoutSignupImport.update({
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileRoute = LayoutProfileImport.update({
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeRoute = LayoutHomeImport.update({
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCommunityRoute = LayoutCommunityImport.update({
  path: '/community',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTradeWriteRoute = LayoutTradeWriteImport.update({
  path: '/write',
  getParentRoute: () => LayoutTradeRoute,
} as any)

const LayoutTradeToRoute = LayoutTradeToImport.update({
  path: '/to',
  getParentRoute: () => LayoutTradeRoute,
} as any)

const LayoutTradeFromRoute = LayoutTradeFromImport.update({
  path: '/from',
  getParentRoute: () => LayoutTradeRoute,
} as any)

const LayoutTradeDetailRoute = LayoutTradeDetailImport.update({
  path: '/detail',
  getParentRoute: () => LayoutTradeRoute,
} as any)

const LayoutSearchResultRoute = LayoutSearchResultImport.update({
  path: '/search/$result',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileWritedRoute = LayoutProfileWritedImport.update({
  path: '/writed',
  getParentRoute: () => LayoutProfileRoute,
} as any)

const LayoutProfilePickedRoute = LayoutProfilePickedImport.update({
  path: '/picked',
  getParentRoute: () => LayoutProfileRoute,
} as any)

const LayoutProfileChatRoute = LayoutProfileChatImport.update({
  path: '/chat',
  getParentRoute: () => LayoutProfileRoute,
} as any)

const LayoutProfileChangelocationRoute =
  LayoutProfileChangelocationImport.update({
    path: '/changelocation',
    getParentRoute: () => LayoutProfileRoute,
  } as any)

const LayoutDiaryWriteRoute = LayoutDiaryWriteImport.update({
  path: '/diary/write',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDiaryRegisterCropRoute = LayoutDiaryRegisterCropImport.update({
  path: '/diary/registerCrop',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCommunityDetailRoute = LayoutCommunityDetailImport.update({
  path: '/detail',
  getParentRoute: () => LayoutCommunityRoute,
} as any)

const LayoutSignupIndexRoute = LayoutSignupIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutSignupRoute,
} as any)

const LayoutSearchIndexRoute = LayoutSearchIndexImport.update({
  path: '/search/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginIndexRoute = LayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDiaryIndexRoute = LayoutDiaryIndexImport.update({
  path: '/diary/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTradeLayoutRoute = LayoutTradeLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutTradeRoute,
} as any)

const LayoutSignupLayoutRoute = LayoutSignupLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutSignupRoute,
} as any)

const LayoutProfileLayoutRoute = LayoutProfileLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutProfileRoute,
} as any)

const LayoutHomeLayoutRoute = LayoutHomeLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutHomeRoute,
} as any)

const LayoutCommunityLayoutRoute = LayoutCommunityLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutCommunityRoute,
} as any)

const LayoutProfileNicknameDiaryRoute = LayoutProfileNicknameDiaryImport.update(
  {
    path: '/$nickname/diary',
    getParentRoute: () => LayoutProfileRoute,
  } as any,
)

const LayoutProfileNicknameCropStorageRoute =
  LayoutProfileNicknameCropStorageImport.update({
    path: '/$nickname/cropStorage',
    getParentRoute: () => LayoutProfileRoute,
  } as any)

const LayoutTradeLayoutIndexRoute = LayoutTradeLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutTradeLayoutRoute,
} as any)

const LayoutProfileAireportIndexRoute = LayoutProfileAireportIndexImport.update(
  {
    path: '/aireport/',
    getParentRoute: () => LayoutProfileRoute,
  } as any,
)

const LayoutProfileLayoutIndexRoute = LayoutProfileLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutProfileLayoutRoute,
} as any)

const LayoutLoginEntranceIndexRoute = LayoutLoginEntranceIndexImport.update({
  path: '/login/entrance/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHomeLayoutIndexRoute = LayoutHomeLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutHomeLayoutRoute,
} as any)

const LayoutDiaryWriteIndexRoute = LayoutDiaryWriteIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutDiaryWriteRoute,
} as any)

const LayoutDiaryRegisterCropIndexRoute =
  LayoutDiaryRegisterCropIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutDiaryRegisterCropRoute,
  } as any)

const LayoutCommunityCreateIndexRoute = LayoutCommunityCreateIndexImport.update(
  {
    path: '/create/',
    getParentRoute: () => LayoutCommunityRoute,
  } as any,
)

const LayoutCommunityLayoutIndexRoute = LayoutCommunityLayoutIndexImport.update(
  {
    path: '/',
    getParentRoute: () => LayoutCommunityLayoutRoute,
  } as any,
)

const LayoutTradeWriteLayoutRoute = LayoutTradeWriteLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutTradeWriteRoute,
} as any)

const LayoutTradeToLayoutRoute = LayoutTradeToLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutTradeToRoute,
} as any)

const LayoutTradeFromLayoutRoute = LayoutTradeFromLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutTradeFromRoute,
} as any)

const LayoutTradeDetailLayoutRoute = LayoutTradeDetailLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutTradeDetailRoute,
} as any)

const LayoutSignupLayout9Route = LayoutSignupLayout9Import.update({
  path: '/9',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout8Route = LayoutSignupLayout8Import.update({
  path: '/8',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout7Route = LayoutSignupLayout7Import.update({
  path: '/7',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout6Route = LayoutSignupLayout6Import.update({
  path: '/6',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout5Route = LayoutSignupLayout5Import.update({
  path: '/5',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout4Route = LayoutSignupLayout4Import.update({
  path: '/4',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout3Route = LayoutSignupLayout3Import.update({
  path: '/3',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout2Route = LayoutSignupLayout2Import.update({
  path: '/2',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout1Route = LayoutSignupLayout1Import.update({
  path: '/1',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSearchResultLayoutRoute = LayoutSearchResultLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutSearchResultRoute,
} as any)

const LayoutProfileWritedLayoutRoute = LayoutProfileWritedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutProfileWritedRoute,
} as any)

const LayoutProfilePickedLayoutRoute = LayoutProfilePickedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutProfilePickedRoute,
} as any)

const LayoutProfileChatLayoutRoute = LayoutProfileChatLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutProfileChatRoute,
} as any)

const LayoutProfileChangelocationLayoutRoute =
  LayoutProfileChangelocationLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProfileChangelocationRoute,
  } as any)

const LayoutDiaryWriteLayoutRoute = LayoutDiaryWriteLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutDiaryWriteRoute,
} as any)

const LayoutDiaryRegisterCropLayoutRoute =
  LayoutDiaryRegisterCropLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutDiaryRegisterCropRoute,
  } as any)

const LayoutDiaryGrowDiaryCropIdRoute = LayoutDiaryGrowDiaryCropIdImport.update(
  {
    path: '/diary/growDiary/$cropId',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutDiaryDetailDiaryIdRoute = LayoutDiaryDetailDiaryIdImport.update({
  path: '/diary/detail/$diaryId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCommunityDetailLayoutRoute =
  LayoutCommunityDetailLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutCommunityDetailRoute,
  } as any)

const LayoutTradeWriteLayoutIndexRoute =
  LayoutTradeWriteLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutTradeWriteLayoutRoute,
  } as any)

const LayoutTradeToLayoutIndexRoute = LayoutTradeToLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutTradeToLayoutRoute,
} as any)

const LayoutTradeFromLayoutIndexRoute = LayoutTradeFromLayoutIndexImport.update(
  {
    path: '/',
    getParentRoute: () => LayoutTradeFromLayoutRoute,
  } as any,
)

const LayoutSearchResultLayoutIndexRoute =
  LayoutSearchResultLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutSearchResultLayoutRoute,
  } as any)

const LayoutProfileWritedLayoutIndexRoute =
  LayoutProfileWritedLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProfileWritedLayoutRoute,
  } as any)

const LayoutProfilePickedLayoutIndexRoute =
  LayoutProfilePickedLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProfilePickedLayoutRoute,
  } as any)

const LayoutProfileChatLayoutIndexRoute =
  LayoutProfileChatLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProfileChatLayoutRoute,
  } as any)

const LayoutProfileChangelocationLayoutIndexRoute =
  LayoutProfileChangelocationLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProfileChangelocationLayoutRoute,
  } as any)

const LayoutTradeDetailLayoutTradeIdRoute =
  LayoutTradeDetailLayoutTradeIdImport.update({
    path: '/$tradeId',
    getParentRoute: () => LayoutTradeDetailLayoutRoute,
  } as any)

const LayoutProfileAireportDetailReportIdRoute =
  LayoutProfileAireportDetailReportIdImport.update({
    path: '/aireport/detail/$reportId',
    getParentRoute: () => LayoutProfileRoute,
  } as any)

const LayoutProfileNicknameDiaryLayoutRoute =
  LayoutProfileNicknameDiaryLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProfileNicknameDiaryRoute,
  } as any)

const LayoutProfileNicknameCropStorageLayoutRoute =
  LayoutProfileNicknameCropStorageLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProfileNicknameCropStorageRoute,
  } as any)

const LayoutDiaryWriteLayout2Route = LayoutDiaryWriteLayout2Import.update({
  path: '/2',
  getParentRoute: () => LayoutDiaryWriteLayoutRoute,
} as any)

const LayoutDiaryWriteLayout1Route = LayoutDiaryWriteLayout1Import.update({
  path: '/1',
  getParentRoute: () => LayoutDiaryWriteLayoutRoute,
} as any)

const LayoutDiaryRegisterCropLayout5Route =
  LayoutDiaryRegisterCropLayout5Import.update({
    path: '/5',
    getParentRoute: () => LayoutDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutDiaryRegisterCropLayout4Route =
  LayoutDiaryRegisterCropLayout4Import.update({
    path: '/4',
    getParentRoute: () => LayoutDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutDiaryRegisterCropLayout3Route =
  LayoutDiaryRegisterCropLayout3Import.update({
    path: '/3',
    getParentRoute: () => LayoutDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutDiaryRegisterCropLayout2Route =
  LayoutDiaryRegisterCropLayout2Import.update({
    path: '/2',
    getParentRoute: () => LayoutDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutDiaryRegisterCropLayout1Route =
  LayoutDiaryRegisterCropLayout1Import.update({
    path: '/1',
    getParentRoute: () => LayoutDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutCommunityDetailLayoutPostIdRoute =
  LayoutCommunityDetailLayoutPostIdImport.update({
    path: '/$postId',
    getParentRoute: () => LayoutCommunityDetailLayoutRoute,
  } as any)

const LayoutProfileNicknameDiaryLayoutIndexRoute =
  LayoutProfileNicknameDiaryLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProfileNicknameDiaryLayoutRoute,
  } as any)

const LayoutProfileNicknameCropStorageLayoutIndexRoute =
  LayoutProfileNicknameCropStorageLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProfileNicknameCropStorageLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/community': {
      id: '/_layout/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof LayoutCommunityImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/community/_layout': {
      id: '/_layout/community/_layout'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof LayoutCommunityLayoutImport
      parentRoute: typeof LayoutCommunityRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/home/_layout': {
      id: '/_layout/home/_layout'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeLayoutImport
      parentRoute: typeof LayoutHomeRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/profile/_layout': {
      id: '/_layout/profile/_layout'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileLayoutImport
      parentRoute: typeof LayoutProfileRoute
    }
    '/_layout/signup': {
      id: '/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/_layout': {
      id: '/_layout/signup/_layout'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupLayoutImport
      parentRoute: typeof LayoutSignupRoute
    }
    '/_layout/trade': {
      id: '/_layout/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof LayoutTradeImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/trade/_layout': {
      id: '/_layout/trade/_layout'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof LayoutTradeLayoutImport
      parentRoute: typeof LayoutTradeRoute
    }
    '/_layout/diary/': {
      id: '/_layout/diary/'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof LayoutDiaryIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/login/': {
      id: '/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/': {
      id: '/_layout/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/': {
      id: '/_layout/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof LayoutSignupIndexImport
      parentRoute: typeof LayoutSignupImport
    }
    '/_layout/community/detail': {
      id: '/_layout/community/detail'
      path: '/detail'
      fullPath: '/community/detail'
      preLoaderRoute: typeof LayoutCommunityDetailImport
      parentRoute: typeof LayoutCommunityImport
    }
    '/_layout/community/detail/_layout': {
      id: '/_layout/community/detail/_layout'
      path: '/detail'
      fullPath: '/community/detail'
      preLoaderRoute: typeof LayoutCommunityDetailLayoutImport
      parentRoute: typeof LayoutCommunityDetailRoute
    }
    '/_layout/diary/detail/$diaryId': {
      id: '/_layout/diary/detail/$diaryId'
      path: '/diary/detail/$diaryId'
      fullPath: '/diary/detail/$diaryId'
      preLoaderRoute: typeof LayoutDiaryDetailDiaryIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/growDiary/$cropId': {
      id: '/_layout/diary/growDiary/$cropId'
      path: '/diary/growDiary/$cropId'
      fullPath: '/diary/growDiary/$cropId'
      preLoaderRoute: typeof LayoutDiaryGrowDiaryCropIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/registerCrop': {
      id: '/_layout/diary/registerCrop'
      path: '/diary/registerCrop'
      fullPath: '/diary/registerCrop'
      preLoaderRoute: typeof LayoutDiaryRegisterCropImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/registerCrop/_layout': {
      id: '/_layout/diary/registerCrop/_layout'
      path: '/diary/registerCrop'
      fullPath: '/diary/registerCrop'
      preLoaderRoute: typeof LayoutDiaryRegisterCropLayoutImport
      parentRoute: typeof LayoutDiaryRegisterCropRoute
    }
    '/_layout/diary/write': {
      id: '/_layout/diary/write'
      path: '/diary/write'
      fullPath: '/diary/write'
      preLoaderRoute: typeof LayoutDiaryWriteImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/diary/write/_layout': {
      id: '/_layout/diary/write/_layout'
      path: '/diary/write'
      fullPath: '/diary/write'
      preLoaderRoute: typeof LayoutDiaryWriteLayoutImport
      parentRoute: typeof LayoutDiaryWriteRoute
    }
    '/_layout/profile/changelocation': {
      id: '/_layout/profile/changelocation'
      path: '/changelocation'
      fullPath: '/profile/changelocation'
      preLoaderRoute: typeof LayoutProfileChangelocationImport
      parentRoute: typeof LayoutProfileImport
    }
    '/_layout/profile/changelocation/_layout': {
      id: '/_layout/profile/changelocation/_layout'
      path: '/changelocation'
      fullPath: '/profile/changelocation'
      preLoaderRoute: typeof LayoutProfileChangelocationLayoutImport
      parentRoute: typeof LayoutProfileChangelocationRoute
    }
    '/_layout/profile/chat': {
      id: '/_layout/profile/chat'
      path: '/chat'
      fullPath: '/profile/chat'
      preLoaderRoute: typeof LayoutProfileChatImport
      parentRoute: typeof LayoutProfileImport
    }
    '/_layout/profile/chat/_layout': {
      id: '/_layout/profile/chat/_layout'
      path: '/chat'
      fullPath: '/profile/chat'
      preLoaderRoute: typeof LayoutProfileChatLayoutImport
      parentRoute: typeof LayoutProfileChatRoute
    }
    '/_layout/profile/picked': {
      id: '/_layout/profile/picked'
      path: '/picked'
      fullPath: '/profile/picked'
      preLoaderRoute: typeof LayoutProfilePickedImport
      parentRoute: typeof LayoutProfileImport
    }
    '/_layout/profile/picked/_layout': {
      id: '/_layout/profile/picked/_layout'
      path: '/picked'
      fullPath: '/profile/picked'
      preLoaderRoute: typeof LayoutProfilePickedLayoutImport
      parentRoute: typeof LayoutProfilePickedRoute
    }
    '/_layout/profile/writed': {
      id: '/_layout/profile/writed'
      path: '/writed'
      fullPath: '/profile/writed'
      preLoaderRoute: typeof LayoutProfileWritedImport
      parentRoute: typeof LayoutProfileImport
    }
    '/_layout/profile/writed/_layout': {
      id: '/_layout/profile/writed/_layout'
      path: '/writed'
      fullPath: '/profile/writed'
      preLoaderRoute: typeof LayoutProfileWritedLayoutImport
      parentRoute: typeof LayoutProfileWritedRoute
    }
    '/_layout/search/$result': {
      id: '/_layout/search/$result'
      path: '/search/$result'
      fullPath: '/search/$result'
      preLoaderRoute: typeof LayoutSearchResultImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/$result/_layout': {
      id: '/_layout/search/$result/_layout'
      path: '/search/$result'
      fullPath: '/search/$result'
      preLoaderRoute: typeof LayoutSearchResultLayoutImport
      parentRoute: typeof LayoutSearchResultRoute
    }
    '/_layout/signup/_layout/1': {
      id: '/_layout/signup/_layout/1'
      path: '/1'
      fullPath: '/signup/1'
      preLoaderRoute: typeof LayoutSignupLayout1Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/2': {
      id: '/_layout/signup/_layout/2'
      path: '/2'
      fullPath: '/signup/2'
      preLoaderRoute: typeof LayoutSignupLayout2Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/3': {
      id: '/_layout/signup/_layout/3'
      path: '/3'
      fullPath: '/signup/3'
      preLoaderRoute: typeof LayoutSignupLayout3Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/4': {
      id: '/_layout/signup/_layout/4'
      path: '/4'
      fullPath: '/signup/4'
      preLoaderRoute: typeof LayoutSignupLayout4Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/5': {
      id: '/_layout/signup/_layout/5'
      path: '/5'
      fullPath: '/signup/5'
      preLoaderRoute: typeof LayoutSignupLayout5Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/6': {
      id: '/_layout/signup/_layout/6'
      path: '/6'
      fullPath: '/signup/6'
      preLoaderRoute: typeof LayoutSignupLayout6Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/7': {
      id: '/_layout/signup/_layout/7'
      path: '/7'
      fullPath: '/signup/7'
      preLoaderRoute: typeof LayoutSignupLayout7Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/8': {
      id: '/_layout/signup/_layout/8'
      path: '/8'
      fullPath: '/signup/8'
      preLoaderRoute: typeof LayoutSignupLayout8Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/9': {
      id: '/_layout/signup/_layout/9'
      path: '/9'
      fullPath: '/signup/9'
      preLoaderRoute: typeof LayoutSignupLayout9Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/trade/detail': {
      id: '/_layout/trade/detail'
      path: '/detail'
      fullPath: '/trade/detail'
      preLoaderRoute: typeof LayoutTradeDetailImport
      parentRoute: typeof LayoutTradeImport
    }
    '/_layout/trade/detail/_layout': {
      id: '/_layout/trade/detail/_layout'
      path: '/detail'
      fullPath: '/trade/detail'
      preLoaderRoute: typeof LayoutTradeDetailLayoutImport
      parentRoute: typeof LayoutTradeDetailRoute
    }
    '/_layout/trade/from': {
      id: '/_layout/trade/from'
      path: '/from'
      fullPath: '/trade/from'
      preLoaderRoute: typeof LayoutTradeFromImport
      parentRoute: typeof LayoutTradeImport
    }
    '/_layout/trade/from/_layout': {
      id: '/_layout/trade/from/_layout'
      path: '/from'
      fullPath: '/trade/from'
      preLoaderRoute: typeof LayoutTradeFromLayoutImport
      parentRoute: typeof LayoutTradeFromRoute
    }
    '/_layout/trade/to': {
      id: '/_layout/trade/to'
      path: '/to'
      fullPath: '/trade/to'
      preLoaderRoute: typeof LayoutTradeToImport
      parentRoute: typeof LayoutTradeImport
    }
    '/_layout/trade/to/_layout': {
      id: '/_layout/trade/to/_layout'
      path: '/to'
      fullPath: '/trade/to'
      preLoaderRoute: typeof LayoutTradeToLayoutImport
      parentRoute: typeof LayoutTradeToRoute
    }
    '/_layout/trade/write': {
      id: '/_layout/trade/write'
      path: '/write'
      fullPath: '/trade/write'
      preLoaderRoute: typeof LayoutTradeWriteImport
      parentRoute: typeof LayoutTradeImport
    }
    '/_layout/trade/write/_layout': {
      id: '/_layout/trade/write/_layout'
      path: '/write'
      fullPath: '/trade/write'
      preLoaderRoute: typeof LayoutTradeWriteLayoutImport
      parentRoute: typeof LayoutTradeWriteRoute
    }
    '/_layout/community/_layout/': {
      id: '/_layout/community/_layout/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof LayoutCommunityLayoutIndexImport
      parentRoute: typeof LayoutCommunityLayoutImport
    }
    '/_layout/community/create/': {
      id: '/_layout/community/create/'
      path: '/create'
      fullPath: '/community/create'
      preLoaderRoute: typeof LayoutCommunityCreateIndexImport
      parentRoute: typeof LayoutCommunityImport
    }
    '/_layout/diary/registerCrop/': {
      id: '/_layout/diary/registerCrop/'
      path: '/'
      fullPath: '/diary/registerCrop/'
      preLoaderRoute: typeof LayoutDiaryRegisterCropIndexImport
      parentRoute: typeof LayoutDiaryRegisterCropImport
    }
    '/_layout/diary/write/': {
      id: '/_layout/diary/write/'
      path: '/'
      fullPath: '/diary/write/'
      preLoaderRoute: typeof LayoutDiaryWriteIndexImport
      parentRoute: typeof LayoutDiaryWriteImport
    }
    '/_layout/home/_layout/': {
      id: '/_layout/home/_layout/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof LayoutHomeLayoutIndexImport
      parentRoute: typeof LayoutHomeLayoutImport
    }
    '/_layout/login/entrance/': {
      id: '/_layout/login/entrance/'
      path: '/login/entrance'
      fullPath: '/login/entrance'
      preLoaderRoute: typeof LayoutLoginEntranceIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/profile/_layout/': {
      id: '/_layout/profile/_layout/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutProfileLayoutIndexImport
      parentRoute: typeof LayoutProfileLayoutImport
    }
    '/_layout/profile/aireport/': {
      id: '/_layout/profile/aireport/'
      path: '/aireport'
      fullPath: '/profile/aireport'
      preLoaderRoute: typeof LayoutProfileAireportIndexImport
      parentRoute: typeof LayoutProfileImport
    }
    '/_layout/trade/_layout/': {
      id: '/_layout/trade/_layout/'
      path: '/'
      fullPath: '/trade/'
      preLoaderRoute: typeof LayoutTradeLayoutIndexImport
      parentRoute: typeof LayoutTradeLayoutImport
    }
    '/_layout/community/detail/_layout/$postId': {
      id: '/_layout/community/detail/_layout/$postId'
      path: '/$postId'
      fullPath: '/community/detail/$postId'
      preLoaderRoute: typeof LayoutCommunityDetailLayoutPostIdImport
      parentRoute: typeof LayoutCommunityDetailLayoutImport
    }
    '/_layout/diary/registerCrop/_layout/1': {
      id: '/_layout/diary/registerCrop/_layout/1'
      path: '/1'
      fullPath: '/diary/registerCrop/1'
      preLoaderRoute: typeof LayoutDiaryRegisterCropLayout1Import
      parentRoute: typeof LayoutDiaryRegisterCropLayoutImport
    }
    '/_layout/diary/registerCrop/_layout/2': {
      id: '/_layout/diary/registerCrop/_layout/2'
      path: '/2'
      fullPath: '/diary/registerCrop/2'
      preLoaderRoute: typeof LayoutDiaryRegisterCropLayout2Import
      parentRoute: typeof LayoutDiaryRegisterCropLayoutImport
    }
    '/_layout/diary/registerCrop/_layout/3': {
      id: '/_layout/diary/registerCrop/_layout/3'
      path: '/3'
      fullPath: '/diary/registerCrop/3'
      preLoaderRoute: typeof LayoutDiaryRegisterCropLayout3Import
      parentRoute: typeof LayoutDiaryRegisterCropLayoutImport
    }
    '/_layout/diary/registerCrop/_layout/4': {
      id: '/_layout/diary/registerCrop/_layout/4'
      path: '/4'
      fullPath: '/diary/registerCrop/4'
      preLoaderRoute: typeof LayoutDiaryRegisterCropLayout4Import
      parentRoute: typeof LayoutDiaryRegisterCropLayoutImport
    }
    '/_layout/diary/registerCrop/_layout/5': {
      id: '/_layout/diary/registerCrop/_layout/5'
      path: '/5'
      fullPath: '/diary/registerCrop/5'
      preLoaderRoute: typeof LayoutDiaryRegisterCropLayout5Import
      parentRoute: typeof LayoutDiaryRegisterCropLayoutImport
    }
    '/_layout/diary/write/_layout/1': {
      id: '/_layout/diary/write/_layout/1'
      path: '/1'
      fullPath: '/diary/write/1'
      preLoaderRoute: typeof LayoutDiaryWriteLayout1Import
      parentRoute: typeof LayoutDiaryWriteLayoutImport
    }
    '/_layout/diary/write/_layout/2': {
      id: '/_layout/diary/write/_layout/2'
      path: '/2'
      fullPath: '/diary/write/2'
      preLoaderRoute: typeof LayoutDiaryWriteLayout2Import
      parentRoute: typeof LayoutDiaryWriteLayoutImport
    }
    '/_layout/profile/$nickname/cropStorage': {
      id: '/_layout/profile/$nickname/cropStorage'
      path: '/$nickname/cropStorage'
      fullPath: '/profile/$nickname/cropStorage'
      preLoaderRoute: typeof LayoutProfileNicknameCropStorageImport
      parentRoute: typeof LayoutProfileImport
    }
    '/_layout/profile/$nickname/cropStorage/_layout': {
      id: '/_layout/profile/$nickname/cropStorage/_layout'
      path: '/$nickname/cropStorage'
      fullPath: '/profile/$nickname/cropStorage'
      preLoaderRoute: typeof LayoutProfileNicknameCropStorageLayoutImport
      parentRoute: typeof LayoutProfileNicknameCropStorageRoute
    }
    '/_layout/profile/$nickname/diary': {
      id: '/_layout/profile/$nickname/diary'
      path: '/$nickname/diary'
      fullPath: '/profile/$nickname/diary'
      preLoaderRoute: typeof LayoutProfileNicknameDiaryImport
      parentRoute: typeof LayoutProfileImport
    }
    '/_layout/profile/$nickname/diary/_layout': {
      id: '/_layout/profile/$nickname/diary/_layout'
      path: '/$nickname/diary'
      fullPath: '/profile/$nickname/diary'
      preLoaderRoute: typeof LayoutProfileNicknameDiaryLayoutImport
      parentRoute: typeof LayoutProfileNicknameDiaryRoute
    }
    '/_layout/profile/aireport/detail/$reportId': {
      id: '/_layout/profile/aireport/detail/$reportId'
      path: '/aireport/detail/$reportId'
      fullPath: '/profile/aireport/detail/$reportId'
      preLoaderRoute: typeof LayoutProfileAireportDetailReportIdImport
      parentRoute: typeof LayoutProfileImport
    }
    '/_layout/trade/detail/_layout/$tradeId': {
      id: '/_layout/trade/detail/_layout/$tradeId'
      path: '/$tradeId'
      fullPath: '/trade/detail/$tradeId'
      preLoaderRoute: typeof LayoutTradeDetailLayoutTradeIdImport
      parentRoute: typeof LayoutTradeDetailLayoutImport
    }
    '/_layout/profile/changelocation/_layout/': {
      id: '/_layout/profile/changelocation/_layout/'
      path: '/'
      fullPath: '/profile/changelocation/'
      preLoaderRoute: typeof LayoutProfileChangelocationLayoutIndexImport
      parentRoute: typeof LayoutProfileChangelocationLayoutImport
    }
    '/_layout/profile/chat/_layout/': {
      id: '/_layout/profile/chat/_layout/'
      path: '/'
      fullPath: '/profile/chat/'
      preLoaderRoute: typeof LayoutProfileChatLayoutIndexImport
      parentRoute: typeof LayoutProfileChatLayoutImport
    }
    '/_layout/profile/picked/_layout/': {
      id: '/_layout/profile/picked/_layout/'
      path: '/'
      fullPath: '/profile/picked/'
      preLoaderRoute: typeof LayoutProfilePickedLayoutIndexImport
      parentRoute: typeof LayoutProfilePickedLayoutImport
    }
    '/_layout/profile/writed/_layout/': {
      id: '/_layout/profile/writed/_layout/'
      path: '/'
      fullPath: '/profile/writed/'
      preLoaderRoute: typeof LayoutProfileWritedLayoutIndexImport
      parentRoute: typeof LayoutProfileWritedLayoutImport
    }
    '/_layout/search/$result/_layout/': {
      id: '/_layout/search/$result/_layout/'
      path: '/'
      fullPath: '/search/$result/'
      preLoaderRoute: typeof LayoutSearchResultLayoutIndexImport
      parentRoute: typeof LayoutSearchResultLayoutImport
    }
    '/_layout/trade/from/_layout/': {
      id: '/_layout/trade/from/_layout/'
      path: '/'
      fullPath: '/trade/from/'
      preLoaderRoute: typeof LayoutTradeFromLayoutIndexImport
      parentRoute: typeof LayoutTradeFromLayoutImport
    }
    '/_layout/trade/to/_layout/': {
      id: '/_layout/trade/to/_layout/'
      path: '/'
      fullPath: '/trade/to/'
      preLoaderRoute: typeof LayoutTradeToLayoutIndexImport
      parentRoute: typeof LayoutTradeToLayoutImport
    }
    '/_layout/trade/write/_layout/': {
      id: '/_layout/trade/write/_layout/'
      path: '/'
      fullPath: '/trade/write/'
      preLoaderRoute: typeof LayoutTradeWriteLayoutIndexImport
      parentRoute: typeof LayoutTradeWriteLayoutImport
    }
    '/_layout/profile/$nickname/cropStorage/_layout/': {
      id: '/_layout/profile/$nickname/cropStorage/_layout/'
      path: '/'
      fullPath: '/profile/$nickname/cropStorage/'
      preLoaderRoute: typeof LayoutProfileNicknameCropStorageLayoutIndexImport
      parentRoute: typeof LayoutProfileNicknameCropStorageLayoutImport
    }
    '/_layout/profile/$nickname/diary/_layout/': {
      id: '/_layout/profile/$nickname/diary/_layout/'
      path: '/'
      fullPath: '/profile/$nickname/diary/'
      preLoaderRoute: typeof LayoutProfileNicknameDiaryLayoutIndexImport
      parentRoute: typeof LayoutProfileNicknameDiaryLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutCommunityRoute: LayoutCommunityRoute.addChildren({
      LayoutCommunityLayoutRoute: LayoutCommunityLayoutRoute.addChildren({
        LayoutCommunityLayoutIndexRoute,
      }),
      LayoutCommunityDetailRoute: LayoutCommunityDetailRoute.addChildren({
        LayoutCommunityDetailLayoutRoute:
          LayoutCommunityDetailLayoutRoute.addChildren({
            LayoutCommunityDetailLayoutPostIdRoute,
          }),
      }),
      LayoutCommunityCreateIndexRoute,
    }),
    LayoutHomeRoute: LayoutHomeRoute.addChildren({
      LayoutHomeLayoutRoute: LayoutHomeLayoutRoute.addChildren({
        LayoutHomeLayoutIndexRoute,
      }),
    }),
    LayoutProfileRoute: LayoutProfileRoute.addChildren({
      LayoutProfileLayoutRoute: LayoutProfileLayoutRoute.addChildren({
        LayoutProfileLayoutIndexRoute,
      }),
      LayoutProfileChangelocationRoute:
        LayoutProfileChangelocationRoute.addChildren({
          LayoutProfileChangelocationLayoutRoute:
            LayoutProfileChangelocationLayoutRoute.addChildren({
              LayoutProfileChangelocationLayoutIndexRoute,
            }),
        }),
      LayoutProfileChatRoute: LayoutProfileChatRoute.addChildren({
        LayoutProfileChatLayoutRoute: LayoutProfileChatLayoutRoute.addChildren({
          LayoutProfileChatLayoutIndexRoute,
        }),
      }),
      LayoutProfilePickedRoute: LayoutProfilePickedRoute.addChildren({
        LayoutProfilePickedLayoutRoute:
          LayoutProfilePickedLayoutRoute.addChildren({
            LayoutProfilePickedLayoutIndexRoute,
          }),
      }),
      LayoutProfileWritedRoute: LayoutProfileWritedRoute.addChildren({
        LayoutProfileWritedLayoutRoute:
          LayoutProfileWritedLayoutRoute.addChildren({
            LayoutProfileWritedLayoutIndexRoute,
          }),
      }),
      LayoutProfileAireportIndexRoute,
      LayoutProfileNicknameCropStorageRoute:
        LayoutProfileNicknameCropStorageRoute.addChildren({
          LayoutProfileNicknameCropStorageLayoutRoute:
            LayoutProfileNicknameCropStorageLayoutRoute.addChildren({
              LayoutProfileNicknameCropStorageLayoutIndexRoute,
            }),
        }),
      LayoutProfileNicknameDiaryRoute:
        LayoutProfileNicknameDiaryRoute.addChildren({
          LayoutProfileNicknameDiaryLayoutRoute:
            LayoutProfileNicknameDiaryLayoutRoute.addChildren({
              LayoutProfileNicknameDiaryLayoutIndexRoute,
            }),
        }),
      LayoutProfileAireportDetailReportIdRoute,
    }),
    LayoutSignupRoute: LayoutSignupRoute.addChildren({
      LayoutSignupLayoutRoute: LayoutSignupLayoutRoute.addChildren({
        LayoutSignupLayout1Route,
        LayoutSignupLayout2Route,
        LayoutSignupLayout3Route,
        LayoutSignupLayout4Route,
        LayoutSignupLayout5Route,
        LayoutSignupLayout6Route,
        LayoutSignupLayout7Route,
        LayoutSignupLayout8Route,
        LayoutSignupLayout9Route,
      }),
      LayoutSignupIndexRoute,
    }),
    LayoutTradeRoute: LayoutTradeRoute.addChildren({
      LayoutTradeLayoutRoute: LayoutTradeLayoutRoute.addChildren({
        LayoutTradeLayoutIndexRoute,
      }),
      LayoutTradeDetailRoute: LayoutTradeDetailRoute.addChildren({
        LayoutTradeDetailLayoutRoute: LayoutTradeDetailLayoutRoute.addChildren({
          LayoutTradeDetailLayoutTradeIdRoute,
        }),
      }),
      LayoutTradeFromRoute: LayoutTradeFromRoute.addChildren({
        LayoutTradeFromLayoutRoute: LayoutTradeFromLayoutRoute.addChildren({
          LayoutTradeFromLayoutIndexRoute,
        }),
      }),
      LayoutTradeToRoute: LayoutTradeToRoute.addChildren({
        LayoutTradeToLayoutRoute: LayoutTradeToLayoutRoute.addChildren({
          LayoutTradeToLayoutIndexRoute,
        }),
      }),
      LayoutTradeWriteRoute: LayoutTradeWriteRoute.addChildren({
        LayoutTradeWriteLayoutRoute: LayoutTradeWriteLayoutRoute.addChildren({
          LayoutTradeWriteLayoutIndexRoute,
        }),
      }),
    }),
    LayoutDiaryIndexRoute,
    LayoutLoginIndexRoute,
    LayoutSearchIndexRoute,
    LayoutDiaryDetailDiaryIdRoute,
    LayoutDiaryGrowDiaryCropIdRoute,
    LayoutDiaryRegisterCropRoute: LayoutDiaryRegisterCropRoute.addChildren({
      LayoutDiaryRegisterCropLayoutRoute:
        LayoutDiaryRegisterCropLayoutRoute.addChildren({
          LayoutDiaryRegisterCropLayout1Route,
          LayoutDiaryRegisterCropLayout2Route,
          LayoutDiaryRegisterCropLayout3Route,
          LayoutDiaryRegisterCropLayout4Route,
          LayoutDiaryRegisterCropLayout5Route,
        }),
      LayoutDiaryRegisterCropIndexRoute,
    }),
    LayoutDiaryWriteRoute: LayoutDiaryWriteRoute.addChildren({
      LayoutDiaryWriteLayoutRoute: LayoutDiaryWriteLayoutRoute.addChildren({
        LayoutDiaryWriteLayout1Route,
        LayoutDiaryWriteLayout2Route,
      }),
      LayoutDiaryWriteIndexRoute,
    }),
    LayoutSearchResultRoute: LayoutSearchResultRoute.addChildren({
      LayoutSearchResultLayoutRoute: LayoutSearchResultLayoutRoute.addChildren({
        LayoutSearchResultLayoutIndexRoute,
      }),
    }),
    LayoutLoginEntranceIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/community",
        "/_layout/home",
        "/_layout/profile",
        "/_layout/signup",
        "/_layout/trade",
        "/_layout/diary/",
        "/_layout/login/",
        "/_layout/search/",
        "/_layout/diary/detail/$diaryId",
        "/_layout/diary/growDiary/$cropId",
        "/_layout/diary/registerCrop",
        "/_layout/diary/write",
        "/_layout/search/$result",
        "/_layout/login/entrance/"
      ]
    },
    "/_layout/community": {
      "filePath": "_layout/community",
      "parent": "/_layout",
      "children": [
        "/_layout/community/_layout",
        "/_layout/community/detail",
        "/_layout/community/create/"
      ]
    },
    "/_layout/community/_layout": {
      "filePath": "_layout/community/_layout.tsx",
      "parent": "/_layout/community",
      "children": [
        "/_layout/community/_layout/"
      ]
    },
    "/_layout/home": {
      "filePath": "_layout/home",
      "parent": "/_layout",
      "children": [
        "/_layout/home/_layout"
      ]
    },
    "/_layout/home/_layout": {
      "filePath": "_layout/home/_layout.tsx",
      "parent": "/_layout/home",
      "children": [
        "/_layout/home/_layout/"
      ]
    },
    "/_layout/profile": {
      "filePath": "_layout/profile",
      "parent": "/_layout",
      "children": [
        "/_layout/profile/_layout",
        "/_layout/profile/changelocation",
        "/_layout/profile/chat",
        "/_layout/profile/picked",
        "/_layout/profile/writed",
        "/_layout/profile/aireport/",
        "/_layout/profile/$nickname/cropStorage",
        "/_layout/profile/$nickname/diary",
        "/_layout/profile/aireport/detail/$reportId"
      ]
    },
    "/_layout/profile/_layout": {
      "filePath": "_layout/profile/_layout.tsx",
      "parent": "/_layout/profile",
      "children": [
        "/_layout/profile/_layout/"
      ]
    },
    "/_layout/signup": {
      "filePath": "_layout/signup",
      "parent": "/_layout",
      "children": [
        "/_layout/signup/_layout",
        "/_layout/signup/"
      ]
    },
    "/_layout/signup/_layout": {
      "filePath": "_layout/signup/_layout.tsx",
      "parent": "/_layout/signup",
      "children": [
        "/_layout/signup/_layout/1",
        "/_layout/signup/_layout/2",
        "/_layout/signup/_layout/3",
        "/_layout/signup/_layout/4",
        "/_layout/signup/_layout/5",
        "/_layout/signup/_layout/6",
        "/_layout/signup/_layout/7",
        "/_layout/signup/_layout/8",
        "/_layout/signup/_layout/9"
      ]
    },
    "/_layout/trade": {
      "filePath": "_layout/trade",
      "parent": "/_layout",
      "children": [
        "/_layout/trade/_layout",
        "/_layout/trade/detail",
        "/_layout/trade/from",
        "/_layout/trade/to",
        "/_layout/trade/write"
      ]
    },
    "/_layout/trade/_layout": {
      "filePath": "_layout/trade/_layout.tsx",
      "parent": "/_layout/trade",
      "children": [
        "/_layout/trade/_layout/"
      ]
    },
    "/_layout/diary/": {
      "filePath": "_layout/diary/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/login/": {
      "filePath": "_layout/login/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/search/": {
      "filePath": "_layout/search/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/signup/": {
      "filePath": "_layout/signup/index.tsx",
      "parent": "/_layout/signup"
    },
    "/_layout/community/detail": {
      "filePath": "_layout/community/detail",
      "parent": "/_layout/community",
      "children": [
        "/_layout/community/detail/_layout"
      ]
    },
    "/_layout/community/detail/_layout": {
      "filePath": "_layout/community/detail/_layout.tsx",
      "parent": "/_layout/community/detail",
      "children": [
        "/_layout/community/detail/_layout/$postId"
      ]
    },
    "/_layout/diary/detail/$diaryId": {
      "filePath": "_layout/diary/detail/$diaryId.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/growDiary/$cropId": {
      "filePath": "_layout/diary/growDiary/$cropId.tsx",
      "parent": "/_layout"
    },
    "/_layout/diary/registerCrop": {
      "filePath": "_layout/diary/registerCrop",
      "parent": "/_layout",
      "children": [
        "/_layout/diary/registerCrop/_layout",
        "/_layout/diary/registerCrop/"
      ]
    },
    "/_layout/diary/registerCrop/_layout": {
      "filePath": "_layout/diary/registerCrop/_layout.tsx",
      "parent": "/_layout/diary/registerCrop",
      "children": [
        "/_layout/diary/registerCrop/_layout/1",
        "/_layout/diary/registerCrop/_layout/2",
        "/_layout/diary/registerCrop/_layout/3",
        "/_layout/diary/registerCrop/_layout/4",
        "/_layout/diary/registerCrop/_layout/5"
      ]
    },
    "/_layout/diary/write": {
      "filePath": "_layout/diary/write",
      "parent": "/_layout",
      "children": [
        "/_layout/diary/write/_layout",
        "/_layout/diary/write/"
      ]
    },
    "/_layout/diary/write/_layout": {
      "filePath": "_layout/diary/write/_layout.tsx",
      "parent": "/_layout/diary/write",
      "children": [
        "/_layout/diary/write/_layout/1",
        "/_layout/diary/write/_layout/2"
      ]
    },
    "/_layout/profile/changelocation": {
      "filePath": "_layout/profile/changelocation",
      "parent": "/_layout/profile",
      "children": [
        "/_layout/profile/changelocation/_layout"
      ]
    },
    "/_layout/profile/changelocation/_layout": {
      "filePath": "_layout/profile/changelocation/_layout.tsx",
      "parent": "/_layout/profile/changelocation",
      "children": [
        "/_layout/profile/changelocation/_layout/"
      ]
    },
    "/_layout/profile/chat": {
      "filePath": "_layout/profile/chat",
      "parent": "/_layout/profile",
      "children": [
        "/_layout/profile/chat/_layout"
      ]
    },
    "/_layout/profile/chat/_layout": {
      "filePath": "_layout/profile/chat/_layout.tsx",
      "parent": "/_layout/profile/chat",
      "children": [
        "/_layout/profile/chat/_layout/"
      ]
    },
    "/_layout/profile/picked": {
      "filePath": "_layout/profile/picked",
      "parent": "/_layout/profile",
      "children": [
        "/_layout/profile/picked/_layout"
      ]
    },
    "/_layout/profile/picked/_layout": {
      "filePath": "_layout/profile/picked/_layout.tsx",
      "parent": "/_layout/profile/picked",
      "children": [
        "/_layout/profile/picked/_layout/"
      ]
    },
    "/_layout/profile/writed": {
      "filePath": "_layout/profile/writed",
      "parent": "/_layout/profile",
      "children": [
        "/_layout/profile/writed/_layout"
      ]
    },
    "/_layout/profile/writed/_layout": {
      "filePath": "_layout/profile/writed/_layout.tsx",
      "parent": "/_layout/profile/writed",
      "children": [
        "/_layout/profile/writed/_layout/"
      ]
    },
    "/_layout/search/$result": {
      "filePath": "_layout/search/$result",
      "parent": "/_layout",
      "children": [
        "/_layout/search/$result/_layout"
      ]
    },
    "/_layout/search/$result/_layout": {
      "filePath": "_layout/search/$result/_layout.tsx",
      "parent": "/_layout/search/$result",
      "children": [
        "/_layout/search/$result/_layout/"
      ]
    },
    "/_layout/signup/_layout/1": {
      "filePath": "_layout/signup/_layout/1.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/2": {
      "filePath": "_layout/signup/_layout/2.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/3": {
      "filePath": "_layout/signup/_layout/3.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/4": {
      "filePath": "_layout/signup/_layout/4.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/5": {
      "filePath": "_layout/signup/_layout/5.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/6": {
      "filePath": "_layout/signup/_layout/6.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/7": {
      "filePath": "_layout/signup/_layout/7.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/8": {
      "filePath": "_layout/signup/_layout/8.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/9": {
      "filePath": "_layout/signup/_layout/9.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/trade/detail": {
      "filePath": "_layout/trade/detail",
      "parent": "/_layout/trade",
      "children": [
        "/_layout/trade/detail/_layout"
      ]
    },
    "/_layout/trade/detail/_layout": {
      "filePath": "_layout/trade/detail/_layout.tsx",
      "parent": "/_layout/trade/detail",
      "children": [
        "/_layout/trade/detail/_layout/$tradeId"
      ]
    },
    "/_layout/trade/from": {
      "filePath": "_layout/trade/from",
      "parent": "/_layout/trade",
      "children": [
        "/_layout/trade/from/_layout"
      ]
    },
    "/_layout/trade/from/_layout": {
      "filePath": "_layout/trade/from/_layout.tsx",
      "parent": "/_layout/trade/from",
      "children": [
        "/_layout/trade/from/_layout/"
      ]
    },
    "/_layout/trade/to": {
      "filePath": "_layout/trade/to",
      "parent": "/_layout/trade",
      "children": [
        "/_layout/trade/to/_layout"
      ]
    },
    "/_layout/trade/to/_layout": {
      "filePath": "_layout/trade/to/_layout.tsx",
      "parent": "/_layout/trade/to",
      "children": [
        "/_layout/trade/to/_layout/"
      ]
    },
    "/_layout/trade/write": {
      "filePath": "_layout/trade/write",
      "parent": "/_layout/trade",
      "children": [
        "/_layout/trade/write/_layout"
      ]
    },
    "/_layout/trade/write/_layout": {
      "filePath": "_layout/trade/write/_layout.tsx",
      "parent": "/_layout/trade/write",
      "children": [
        "/_layout/trade/write/_layout/"
      ]
    },
    "/_layout/community/_layout/": {
      "filePath": "_layout/community/_layout/index.tsx",
      "parent": "/_layout/community/_layout"
    },
    "/_layout/community/create/": {
      "filePath": "_layout/community/create/index.tsx",
      "parent": "/_layout/community"
    },
    "/_layout/diary/registerCrop/": {
      "filePath": "_layout/diary/registerCrop/index.tsx",
      "parent": "/_layout/diary/registerCrop"
    },
    "/_layout/diary/write/": {
      "filePath": "_layout/diary/write/index.tsx",
      "parent": "/_layout/diary/write"
    },
    "/_layout/home/_layout/": {
      "filePath": "_layout/home/_layout/index.tsx",
      "parent": "/_layout/home/_layout"
    },
    "/_layout/login/entrance/": {
      "filePath": "_layout/login/entrance/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/profile/_layout/": {
      "filePath": "_layout/profile/_layout/index.tsx",
      "parent": "/_layout/profile/_layout"
    },
    "/_layout/profile/aireport/": {
      "filePath": "_layout/profile/aireport/index.tsx",
      "parent": "/_layout/profile"
    },
    "/_layout/trade/_layout/": {
      "filePath": "_layout/trade/_layout/index.tsx",
      "parent": "/_layout/trade/_layout"
    },
    "/_layout/community/detail/_layout/$postId": {
      "filePath": "_layout/community/detail/_layout/$postId.tsx",
      "parent": "/_layout/community/detail/_layout"
    },
    "/_layout/diary/registerCrop/_layout/1": {
      "filePath": "_layout/diary/registerCrop/_layout/1.tsx",
      "parent": "/_layout/diary/registerCrop/_layout"
    },
    "/_layout/diary/registerCrop/_layout/2": {
      "filePath": "_layout/diary/registerCrop/_layout/2.tsx",
      "parent": "/_layout/diary/registerCrop/_layout"
    },
    "/_layout/diary/registerCrop/_layout/3": {
      "filePath": "_layout/diary/registerCrop/_layout/3.tsx",
      "parent": "/_layout/diary/registerCrop/_layout"
    },
    "/_layout/diary/registerCrop/_layout/4": {
      "filePath": "_layout/diary/registerCrop/_layout/4.tsx",
      "parent": "/_layout/diary/registerCrop/_layout"
    },
    "/_layout/diary/registerCrop/_layout/5": {
      "filePath": "_layout/diary/registerCrop/_layout/5.tsx",
      "parent": "/_layout/diary/registerCrop/_layout"
    },
    "/_layout/diary/write/_layout/1": {
      "filePath": "_layout/diary/write/_layout/1.tsx",
      "parent": "/_layout/diary/write/_layout"
    },
    "/_layout/diary/write/_layout/2": {
      "filePath": "_layout/diary/write/_layout/2.tsx",
      "parent": "/_layout/diary/write/_layout"
    },
    "/_layout/profile/$nickname/cropStorage": {
      "filePath": "_layout/profile/$nickname/cropStorage",
      "parent": "/_layout/profile",
      "children": [
        "/_layout/profile/$nickname/cropStorage/_layout"
      ]
    },
    "/_layout/profile/$nickname/cropStorage/_layout": {
      "filePath": "_layout/profile/$nickname/cropStorage/_layout.tsx",
      "parent": "/_layout/profile/$nickname/cropStorage",
      "children": [
        "/_layout/profile/$nickname/cropStorage/_layout/"
      ]
    },
    "/_layout/profile/$nickname/diary": {
      "filePath": "_layout/profile/$nickname/diary",
      "parent": "/_layout/profile",
      "children": [
        "/_layout/profile/$nickname/diary/_layout"
      ]
    },
    "/_layout/profile/$nickname/diary/_layout": {
      "filePath": "_layout/profile/$nickname/diary/_layout.tsx",
      "parent": "/_layout/profile/$nickname/diary",
      "children": [
        "/_layout/profile/$nickname/diary/_layout/"
      ]
    },
    "/_layout/profile/aireport/detail/$reportId": {
      "filePath": "_layout/profile/aireport/detail/$reportId.tsx",
      "parent": "/_layout/profile"
    },
    "/_layout/trade/detail/_layout/$tradeId": {
      "filePath": "_layout/trade/detail/_layout/$tradeId.tsx",
      "parent": "/_layout/trade/detail/_layout"
    },
    "/_layout/profile/changelocation/_layout/": {
      "filePath": "_layout/profile/changelocation/_layout/index.tsx",
      "parent": "/_layout/profile/changelocation/_layout"
    },
    "/_layout/profile/chat/_layout/": {
      "filePath": "_layout/profile/chat/_layout/index.tsx",
      "parent": "/_layout/profile/chat/_layout"
    },
    "/_layout/profile/picked/_layout/": {
      "filePath": "_layout/profile/picked/_layout/index.tsx",
      "parent": "/_layout/profile/picked/_layout"
    },
    "/_layout/profile/writed/_layout/": {
      "filePath": "_layout/profile/writed/_layout/index.tsx",
      "parent": "/_layout/profile/writed/_layout"
    },
    "/_layout/search/$result/_layout/": {
      "filePath": "_layout/search/$result/_layout/index.tsx",
      "parent": "/_layout/search/$result/_layout"
    },
    "/_layout/trade/from/_layout/": {
      "filePath": "_layout/trade/from/_layout/index.tsx",
      "parent": "/_layout/trade/from/_layout"
    },
    "/_layout/trade/to/_layout/": {
      "filePath": "_layout/trade/to/_layout/index.tsx",
      "parent": "/_layout/trade/to/_layout"
    },
    "/_layout/trade/write/_layout/": {
      "filePath": "_layout/trade/write/_layout/index.tsx",
      "parent": "/_layout/trade/write/_layout"
    },
    "/_layout/profile/$nickname/cropStorage/_layout/": {
      "filePath": "_layout/profile/$nickname/cropStorage/_layout/index.tsx",
      "parent": "/_layout/profile/$nickname/cropStorage/_layout"
    },
    "/_layout/profile/$nickname/diary/_layout/": {
      "filePath": "_layout/profile/$nickname/diary/_layout/index.tsx",
      "parent": "/_layout/profile/$nickname/diary/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
