/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutProtectedImport } from './routes/_layout/_protected'
import { Route as LayoutSignupIndexImport } from './routes/_layout/signup/index'
import { Route as LayoutLoginIndexImport } from './routes/_layout/login/index'
import { Route as LayoutSignupLayoutImport } from './routes/_layout/signup/_layout'
import { Route as LayoutProtectedHomeImport } from './routes/_layout/_protected/_home'
import { Route as LayoutLoginEntranceIndexImport } from './routes/_layout/login/entrance/index'
import { Route as LayoutProtectedSearchIndexImport } from './routes/_layout/_protected/search/index'
import { Route as LayoutProtectedHomeIndexImport } from './routes/_layout/_protected/_home/index'
import { Route as LayoutSignupLayoutAdditionalImport } from './routes/_layout/signup/_layout/additional'
import { Route as LayoutSignupLayout9Import } from './routes/_layout/signup/_layout/9'
import { Route as LayoutSignupLayout8Import } from './routes/_layout/signup/_layout/8'
import { Route as LayoutSignupLayout7Import } from './routes/_layout/signup/_layout/7'
import { Route as LayoutSignupLayout6Import } from './routes/_layout/signup/_layout/6'
import { Route as LayoutSignupLayout5Import } from './routes/_layout/signup/_layout/5'
import { Route as LayoutSignupLayout4Import } from './routes/_layout/signup/_layout/4'
import { Route as LayoutSignupLayout3Import } from './routes/_layout/signup/_layout/3'
import { Route as LayoutSignupLayout2Import } from './routes/_layout/signup/_layout/2'
import { Route as LayoutSignupLayout1Import } from './routes/_layout/signup/_layout/1'
import { Route as LayoutProtectedTradeLayoutImport } from './routes/_layout/_protected/trade/_layout'
import { Route as LayoutProtectedProfileLayoutImport } from './routes/_layout/_protected/profile/_layout'
import { Route as LayoutProtectedDiaryLayoutImport } from './routes/_layout/_protected/diary/_layout'
import { Route as LayoutProtectedCommunityLayoutImport } from './routes/_layout/_protected/community/_layout'
import { Route as LayoutProtectedTradeLayoutIndexImport } from './routes/_layout/_protected/trade/_layout/index'
import { Route as LayoutProtectedProfileAireportIndexImport } from './routes/_layout/_protected/profile/aireport/index'
import { Route as LayoutProtectedProfileLayoutIndexImport } from './routes/_layout/_protected/profile/_layout/index'
import { Route as LayoutProtectedDiaryWriteIndexImport } from './routes/_layout/_protected/diary/write/index'
import { Route as LayoutProtectedDiaryRegisterCropIndexImport } from './routes/_layout/_protected/diary/registerCrop/index'
import { Route as LayoutProtectedDiaryLayoutIndexImport } from './routes/_layout/_protected/diary/_layout/index'
import { Route as LayoutProtectedCommunityCreateIndexImport } from './routes/_layout/_protected/community/create/index'
import { Route as LayoutProtectedCommunityLayoutIndexImport } from './routes/_layout/_protected/community/_layout/index'
import { Route as LayoutProtectedTradeWriteLayoutImport } from './routes/_layout/_protected/trade/write/_layout'
import { Route as LayoutProtectedTradeToLayoutImport } from './routes/_layout/_protected/trade/to/_layout'
import { Route as LayoutProtectedTradeFromLayoutImport } from './routes/_layout/_protected/trade/from/_layout'
import { Route as LayoutProtectedTradeDetailLayoutImport } from './routes/_layout/_protected/trade/detail/_layout'
import { Route as LayoutProtectedSearchResultLayoutImport } from './routes/_layout/_protected/search/$result/_layout'
import { Route as LayoutProtectedProfileWritedLayoutImport } from './routes/_layout/_protected/profile/writed/_layout'
import { Route as LayoutProtectedProfilePickedLayoutImport } from './routes/_layout/_protected/profile/picked/_layout'
import { Route as LayoutProtectedProfileChatLayoutImport } from './routes/_layout/_protected/profile/chat/_layout'
import { Route as LayoutProtectedProfileChangelocationLayoutImport } from './routes/_layout/_protected/profile/changelocation/_layout'
import { Route as LayoutProtectedProfileUserIdLayoutImport } from './routes/_layout/_protected/profile/$userId/_layout'
import { Route as LayoutProtectedDiaryWriteLayoutImport } from './routes/_layout/_protected/diary/write/_layout'
import { Route as LayoutProtectedDiaryRegisterCropLayoutImport } from './routes/_layout/_protected/diary/registerCrop/_layout'
import { Route as LayoutProtectedDiaryGrowDiaryLayoutImport } from './routes/_layout/_protected/diary/growDiary/_layout'
import { Route as LayoutProtectedDiaryDetailLayoutImport } from './routes/_layout/_protected/diary/detail/_layout'
import { Route as LayoutProtectedCommunityDetailLayoutImport } from './routes/_layout/_protected/community/detail/_layout'
import { Route as LayoutProtectedTradeWriteLayoutIndexImport } from './routes/_layout/_protected/trade/write/_layout/index'
import { Route as LayoutProtectedTradeToLayoutIndexImport } from './routes/_layout/_protected/trade/to/_layout/index'
import { Route as LayoutProtectedTradeFromLayoutIndexImport } from './routes/_layout/_protected/trade/from/_layout/index'
import { Route as LayoutProtectedSearchResultLayoutIndexImport } from './routes/_layout/_protected/search/$result/_layout/index'
import { Route as LayoutProtectedProfileWritedLayoutIndexImport } from './routes/_layout/_protected/profile/writed/_layout/index'
import { Route as LayoutProtectedProfilePickedLayoutIndexImport } from './routes/_layout/_protected/profile/picked/_layout/index'
import { Route as LayoutProtectedProfileChatLayoutIndexImport } from './routes/_layout/_protected/profile/chat/_layout/index'
import { Route as LayoutProtectedProfileChangelocationLayoutIndexImport } from './routes/_layout/_protected/profile/changelocation/_layout/index'
import { Route as LayoutProtectedProfileUserIdLayoutIndexImport } from './routes/_layout/_protected/profile/$userId/_layout/index'
import { Route as LayoutProtectedTradeDetailLayoutTradeIdImport } from './routes/_layout/_protected/trade/detail/_layout/$tradeId'
import { Route as LayoutProtectedProfileAireportDetailReportIdImport } from './routes/_layout/_protected/profile/aireport/detail/$reportId'
import { Route as LayoutProtectedProfileUserIdDiaryLayoutImport } from './routes/_layout/_protected/profile/$userId/diary/_layout'
import { Route as LayoutProtectedProfileUserIdCropStorageLayoutImport } from './routes/_layout/_protected/profile/$userId/cropStorage/_layout'
import { Route as LayoutProtectedDiaryWriteLayout2Import } from './routes/_layout/_protected/diary/write/_layout/2'
import { Route as LayoutProtectedDiaryWriteLayout1Import } from './routes/_layout/_protected/diary/write/_layout/1'
import { Route as LayoutProtectedDiaryRegisterCropLayout5Import } from './routes/_layout/_protected/diary/registerCrop/_layout/5'
import { Route as LayoutProtectedDiaryRegisterCropLayout4Import } from './routes/_layout/_protected/diary/registerCrop/_layout/4'
import { Route as LayoutProtectedDiaryRegisterCropLayout3Import } from './routes/_layout/_protected/diary/registerCrop/_layout/3'
import { Route as LayoutProtectedDiaryRegisterCropLayout2Import } from './routes/_layout/_protected/diary/registerCrop/_layout/2'
import { Route as LayoutProtectedDiaryRegisterCropLayout1Import } from './routes/_layout/_protected/diary/registerCrop/_layout/1'
import { Route as LayoutProtectedDiaryGrowDiaryLayoutCropIdImport } from './routes/_layout/_protected/diary/growDiary/_layout/$cropId'
import { Route as LayoutProtectedDiaryDetailLayoutCropDiaryIdImport } from './routes/_layout/_protected/diary/detail/_layout/$cropDiaryId'
import { Route as LayoutProtectedCommunityDetailLayoutPostIdImport } from './routes/_layout/_protected/community/detail/_layout/$postId'
import { Route as LayoutProtectedProfileUserIdDiaryLayoutIndexImport } from './routes/_layout/_protected/profile/$userId/diary/_layout/index'
import { Route as LayoutProtectedProfileUserIdCropStorageLayoutIndexImport } from './routes/_layout/_protected/profile/$userId/cropStorage/_layout/index'

// Create Virtual Routes

const LayoutSignupImport = createFileRoute('/_layout/signup')()
const LayoutProtectedTradeImport = createFileRoute(
  '/_layout/_protected/trade',
)()
const LayoutProtectedProfileImport = createFileRoute(
  '/_layout/_protected/profile',
)()
const LayoutProtectedDiaryImport = createFileRoute(
  '/_layout/_protected/diary',
)()
const LayoutProtectedCommunityImport = createFileRoute(
  '/_layout/_protected/community',
)()
const LayoutProtectedTradeWriteImport = createFileRoute(
  '/_layout/_protected/trade/write',
)()
const LayoutProtectedTradeToImport = createFileRoute(
  '/_layout/_protected/trade/to',
)()
const LayoutProtectedTradeFromImport = createFileRoute(
  '/_layout/_protected/trade/from',
)()
const LayoutProtectedTradeDetailImport = createFileRoute(
  '/_layout/_protected/trade/detail',
)()
const LayoutProtectedSearchResultImport = createFileRoute(
  '/_layout/_protected/search/$result',
)()
const LayoutProtectedProfileWritedImport = createFileRoute(
  '/_layout/_protected/profile/writed',
)()
const LayoutProtectedProfilePickedImport = createFileRoute(
  '/_layout/_protected/profile/picked',
)()
const LayoutProtectedProfileChatImport = createFileRoute(
  '/_layout/_protected/profile/chat',
)()
const LayoutProtectedProfileChangelocationImport = createFileRoute(
  '/_layout/_protected/profile/changelocation',
)()
const LayoutProtectedProfileUserIdImport = createFileRoute(
  '/_layout/_protected/profile/$userId',
)()
const LayoutProtectedDiaryWriteImport = createFileRoute(
  '/_layout/_protected/diary/write',
)()
const LayoutProtectedDiaryRegisterCropImport = createFileRoute(
  '/_layout/_protected/diary/registerCrop',
)()
const LayoutProtectedDiaryGrowDiaryImport = createFileRoute(
  '/_layout/_protected/diary/growDiary',
)()
const LayoutProtectedDiaryDetailImport = createFileRoute(
  '/_layout/_protected/diary/detail',
)()
const LayoutProtectedCommunityDetailImport = createFileRoute(
  '/_layout/_protected/community/detail',
)()
const LayoutProtectedProfileUserIdDiaryImport = createFileRoute(
  '/_layout/_protected/profile/$userId/diary',
)()
const LayoutProtectedProfileUserIdCropStorageImport = createFileRoute(
  '/_layout/_protected/profile/$userId/cropStorage',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSignupRoute = LayoutSignupImport.update({
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProtectedRoute = LayoutProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProtectedTradeRoute = LayoutProtectedTradeImport.update({
  path: '/trade',
  getParentRoute: () => LayoutProtectedRoute,
} as any)

const LayoutProtectedProfileRoute = LayoutProtectedProfileImport.update({
  path: '/profile',
  getParentRoute: () => LayoutProtectedRoute,
} as any)

const LayoutProtectedDiaryRoute = LayoutProtectedDiaryImport.update({
  path: '/diary',
  getParentRoute: () => LayoutProtectedRoute,
} as any)

const LayoutProtectedCommunityRoute = LayoutProtectedCommunityImport.update({
  path: '/community',
  getParentRoute: () => LayoutProtectedRoute,
} as any)

const LayoutSignupIndexRoute = LayoutSignupIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutSignupRoute,
} as any)

const LayoutLoginIndexRoute = LayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSignupLayoutRoute = LayoutSignupLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutSignupRoute,
} as any)

const LayoutProtectedHomeRoute = LayoutProtectedHomeImport.update({
  id: '/_home',
  getParentRoute: () => LayoutProtectedRoute,
} as any)

const LayoutProtectedTradeWriteRoute = LayoutProtectedTradeWriteImport.update({
  path: '/write',
  getParentRoute: () => LayoutProtectedTradeRoute,
} as any)

const LayoutProtectedTradeToRoute = LayoutProtectedTradeToImport.update({
  path: '/to',
  getParentRoute: () => LayoutProtectedTradeRoute,
} as any)

const LayoutProtectedTradeFromRoute = LayoutProtectedTradeFromImport.update({
  path: '/from',
  getParentRoute: () => LayoutProtectedTradeRoute,
} as any)

const LayoutProtectedTradeDetailRoute = LayoutProtectedTradeDetailImport.update(
  {
    path: '/detail',
    getParentRoute: () => LayoutProtectedTradeRoute,
  } as any,
)

const LayoutProtectedSearchResultRoute =
  LayoutProtectedSearchResultImport.update({
    path: '/search/$result',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)

const LayoutProtectedProfileWritedRoute =
  LayoutProtectedProfileWritedImport.update({
    path: '/writed',
    getParentRoute: () => LayoutProtectedProfileRoute,
  } as any)

const LayoutProtectedProfilePickedRoute =
  LayoutProtectedProfilePickedImport.update({
    path: '/picked',
    getParentRoute: () => LayoutProtectedProfileRoute,
  } as any)

const LayoutProtectedProfileChatRoute = LayoutProtectedProfileChatImport.update(
  {
    path: '/chat',
    getParentRoute: () => LayoutProtectedProfileRoute,
  } as any,
)

const LayoutProtectedProfileChangelocationRoute =
  LayoutProtectedProfileChangelocationImport.update({
    path: '/changelocation',
    getParentRoute: () => LayoutProtectedProfileRoute,
  } as any)

const LayoutProtectedProfileUserIdRoute =
  LayoutProtectedProfileUserIdImport.update({
    path: '/$userId',
    getParentRoute: () => LayoutProtectedProfileRoute,
  } as any)

const LayoutProtectedDiaryWriteRoute = LayoutProtectedDiaryWriteImport.update({
  path: '/write',
  getParentRoute: () => LayoutProtectedDiaryRoute,
} as any)

const LayoutProtectedDiaryRegisterCropRoute =
  LayoutProtectedDiaryRegisterCropImport.update({
    path: '/registerCrop',
    getParentRoute: () => LayoutProtectedDiaryRoute,
  } as any)

const LayoutProtectedDiaryGrowDiaryRoute =
  LayoutProtectedDiaryGrowDiaryImport.update({
    path: '/growDiary',
    getParentRoute: () => LayoutProtectedDiaryRoute,
  } as any)

const LayoutProtectedDiaryDetailRoute = LayoutProtectedDiaryDetailImport.update(
  {
    path: '/detail',
    getParentRoute: () => LayoutProtectedDiaryRoute,
  } as any,
)

const LayoutProtectedCommunityDetailRoute =
  LayoutProtectedCommunityDetailImport.update({
    path: '/detail',
    getParentRoute: () => LayoutProtectedCommunityRoute,
  } as any)

const LayoutLoginEntranceIndexRoute = LayoutLoginEntranceIndexImport.update({
  path: '/login/entrance/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProtectedSearchIndexRoute = LayoutProtectedSearchIndexImport.update(
  {
    path: '/search/',
    getParentRoute: () => LayoutProtectedRoute,
  } as any,
)

const LayoutProtectedHomeIndexRoute = LayoutProtectedHomeIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutProtectedHomeRoute,
} as any)

const LayoutSignupLayoutAdditionalRoute =
  LayoutSignupLayoutAdditionalImport.update({
    path: '/additional',
    getParentRoute: () => LayoutSignupLayoutRoute,
  } as any)

const LayoutSignupLayout9Route = LayoutSignupLayout9Import.update({
  path: '/9',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout8Route = LayoutSignupLayout8Import.update({
  path: '/8',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout7Route = LayoutSignupLayout7Import.update({
  path: '/7',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout6Route = LayoutSignupLayout6Import.update({
  path: '/6',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout5Route = LayoutSignupLayout5Import.update({
  path: '/5',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout4Route = LayoutSignupLayout4Import.update({
  path: '/4',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout3Route = LayoutSignupLayout3Import.update({
  path: '/3',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout2Route = LayoutSignupLayout2Import.update({
  path: '/2',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutSignupLayout1Route = LayoutSignupLayout1Import.update({
  path: '/1',
  getParentRoute: () => LayoutSignupLayoutRoute,
} as any)

const LayoutProtectedTradeLayoutRoute = LayoutProtectedTradeLayoutImport.update(
  {
    id: '/_layout',
    getParentRoute: () => LayoutProtectedTradeRoute,
  } as any,
)

const LayoutProtectedProfileLayoutRoute =
  LayoutProtectedProfileLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedProfileRoute,
  } as any)

const LayoutProtectedDiaryLayoutRoute = LayoutProtectedDiaryLayoutImport.update(
  {
    id: '/_layout',
    getParentRoute: () => LayoutProtectedDiaryRoute,
  } as any,
)

const LayoutProtectedCommunityLayoutRoute =
  LayoutProtectedCommunityLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedCommunityRoute,
  } as any)

const LayoutProtectedProfileUserIdDiaryRoute =
  LayoutProtectedProfileUserIdDiaryImport.update({
    path: '/diary',
    getParentRoute: () => LayoutProtectedProfileUserIdRoute,
  } as any)

const LayoutProtectedProfileUserIdCropStorageRoute =
  LayoutProtectedProfileUserIdCropStorageImport.update({
    path: '/cropStorage',
    getParentRoute: () => LayoutProtectedProfileUserIdRoute,
  } as any)

const LayoutProtectedTradeLayoutIndexRoute =
  LayoutProtectedTradeLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedTradeLayoutRoute,
  } as any)

const LayoutProtectedProfileAireportIndexRoute =
  LayoutProtectedProfileAireportIndexImport.update({
    path: '/aireport/',
    getParentRoute: () => LayoutProtectedProfileRoute,
  } as any)

const LayoutProtectedProfileLayoutIndexRoute =
  LayoutProtectedProfileLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedProfileLayoutRoute,
  } as any)

const LayoutProtectedDiaryWriteIndexRoute =
  LayoutProtectedDiaryWriteIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedDiaryWriteRoute,
  } as any)

const LayoutProtectedDiaryRegisterCropIndexRoute =
  LayoutProtectedDiaryRegisterCropIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedDiaryRegisterCropRoute,
  } as any)

const LayoutProtectedDiaryLayoutIndexRoute =
  LayoutProtectedDiaryLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedDiaryLayoutRoute,
  } as any)

const LayoutProtectedCommunityCreateIndexRoute =
  LayoutProtectedCommunityCreateIndexImport.update({
    path: '/create/',
    getParentRoute: () => LayoutProtectedCommunityRoute,
  } as any)

const LayoutProtectedCommunityLayoutIndexRoute =
  LayoutProtectedCommunityLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedCommunityLayoutRoute,
  } as any)

const LayoutProtectedTradeWriteLayoutRoute =
  LayoutProtectedTradeWriteLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedTradeWriteRoute,
  } as any)

const LayoutProtectedTradeToLayoutRoute =
  LayoutProtectedTradeToLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedTradeToRoute,
  } as any)

const LayoutProtectedTradeFromLayoutRoute =
  LayoutProtectedTradeFromLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedTradeFromRoute,
  } as any)

const LayoutProtectedTradeDetailLayoutRoute =
  LayoutProtectedTradeDetailLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedTradeDetailRoute,
  } as any)

const LayoutProtectedSearchResultLayoutRoute =
  LayoutProtectedSearchResultLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedSearchResultRoute,
  } as any)

const LayoutProtectedProfileWritedLayoutRoute =
  LayoutProtectedProfileWritedLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedProfileWritedRoute,
  } as any)

const LayoutProtectedProfilePickedLayoutRoute =
  LayoutProtectedProfilePickedLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedProfilePickedRoute,
  } as any)

const LayoutProtectedProfileChatLayoutRoute =
  LayoutProtectedProfileChatLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedProfileChatRoute,
  } as any)

const LayoutProtectedProfileChangelocationLayoutRoute =
  LayoutProtectedProfileChangelocationLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedProfileChangelocationRoute,
  } as any)

const LayoutProtectedProfileUserIdLayoutRoute =
  LayoutProtectedProfileUserIdLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedProfileUserIdRoute,
  } as any)

const LayoutProtectedDiaryWriteLayoutRoute =
  LayoutProtectedDiaryWriteLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedDiaryWriteRoute,
  } as any)

const LayoutProtectedDiaryRegisterCropLayoutRoute =
  LayoutProtectedDiaryRegisterCropLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedDiaryRegisterCropRoute,
  } as any)

const LayoutProtectedDiaryGrowDiaryLayoutRoute =
  LayoutProtectedDiaryGrowDiaryLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedDiaryGrowDiaryRoute,
  } as any)

const LayoutProtectedDiaryDetailLayoutRoute =
  LayoutProtectedDiaryDetailLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedDiaryDetailRoute,
  } as any)

const LayoutProtectedCommunityDetailLayoutRoute =
  LayoutProtectedCommunityDetailLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedCommunityDetailRoute,
  } as any)

const LayoutProtectedTradeWriteLayoutIndexRoute =
  LayoutProtectedTradeWriteLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedTradeWriteLayoutRoute,
  } as any)

const LayoutProtectedTradeToLayoutIndexRoute =
  LayoutProtectedTradeToLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedTradeToLayoutRoute,
  } as any)

const LayoutProtectedTradeFromLayoutIndexRoute =
  LayoutProtectedTradeFromLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedTradeFromLayoutRoute,
  } as any)

const LayoutProtectedSearchResultLayoutIndexRoute =
  LayoutProtectedSearchResultLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedSearchResultLayoutRoute,
  } as any)

const LayoutProtectedProfileWritedLayoutIndexRoute =
  LayoutProtectedProfileWritedLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedProfileWritedLayoutRoute,
  } as any)

const LayoutProtectedProfilePickedLayoutIndexRoute =
  LayoutProtectedProfilePickedLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedProfilePickedLayoutRoute,
  } as any)

const LayoutProtectedProfileChatLayoutIndexRoute =
  LayoutProtectedProfileChatLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedProfileChatLayoutRoute,
  } as any)

const LayoutProtectedProfileChangelocationLayoutIndexRoute =
  LayoutProtectedProfileChangelocationLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedProfileChangelocationLayoutRoute,
  } as any)

const LayoutProtectedProfileUserIdLayoutIndexRoute =
  LayoutProtectedProfileUserIdLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedProfileUserIdLayoutRoute,
  } as any)

const LayoutProtectedTradeDetailLayoutTradeIdRoute =
  LayoutProtectedTradeDetailLayoutTradeIdImport.update({
    path: '/$tradeId',
    getParentRoute: () => LayoutProtectedTradeDetailLayoutRoute,
  } as any)

const LayoutProtectedProfileAireportDetailReportIdRoute =
  LayoutProtectedProfileAireportDetailReportIdImport.update({
    path: '/aireport/detail/$reportId',
    getParentRoute: () => LayoutProtectedProfileRoute,
  } as any)

const LayoutProtectedProfileUserIdDiaryLayoutRoute =
  LayoutProtectedProfileUserIdDiaryLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedProfileUserIdDiaryRoute,
  } as any)

const LayoutProtectedProfileUserIdCropStorageLayoutRoute =
  LayoutProtectedProfileUserIdCropStorageLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedProfileUserIdCropStorageRoute,
  } as any)

const LayoutProtectedDiaryWriteLayout2Route =
  LayoutProtectedDiaryWriteLayout2Import.update({
    path: '/2',
    getParentRoute: () => LayoutProtectedDiaryWriteLayoutRoute,
  } as any)

const LayoutProtectedDiaryWriteLayout1Route =
  LayoutProtectedDiaryWriteLayout1Import.update({
    path: '/1',
    getParentRoute: () => LayoutProtectedDiaryWriteLayoutRoute,
  } as any)

const LayoutProtectedDiaryRegisterCropLayout5Route =
  LayoutProtectedDiaryRegisterCropLayout5Import.update({
    path: '/5',
    getParentRoute: () => LayoutProtectedDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutProtectedDiaryRegisterCropLayout4Route =
  LayoutProtectedDiaryRegisterCropLayout4Import.update({
    path: '/4',
    getParentRoute: () => LayoutProtectedDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutProtectedDiaryRegisterCropLayout3Route =
  LayoutProtectedDiaryRegisterCropLayout3Import.update({
    path: '/3',
    getParentRoute: () => LayoutProtectedDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutProtectedDiaryRegisterCropLayout2Route =
  LayoutProtectedDiaryRegisterCropLayout2Import.update({
    path: '/2',
    getParentRoute: () => LayoutProtectedDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutProtectedDiaryRegisterCropLayout1Route =
  LayoutProtectedDiaryRegisterCropLayout1Import.update({
    path: '/1',
    getParentRoute: () => LayoutProtectedDiaryRegisterCropLayoutRoute,
  } as any)

const LayoutProtectedDiaryGrowDiaryLayoutCropIdRoute =
  LayoutProtectedDiaryGrowDiaryLayoutCropIdImport.update({
    path: '/$cropId',
    getParentRoute: () => LayoutProtectedDiaryGrowDiaryLayoutRoute,
  } as any)

const LayoutProtectedDiaryDetailLayoutCropDiaryIdRoute =
  LayoutProtectedDiaryDetailLayoutCropDiaryIdImport.update({
    path: '/$cropDiaryId',
    getParentRoute: () => LayoutProtectedDiaryDetailLayoutRoute,
  } as any)

const LayoutProtectedCommunityDetailLayoutPostIdRoute =
  LayoutProtectedCommunityDetailLayoutPostIdImport.update({
    path: '/$postId',
    getParentRoute: () => LayoutProtectedCommunityDetailLayoutRoute,
  } as any)

const LayoutProtectedProfileUserIdDiaryLayoutIndexRoute =
  LayoutProtectedProfileUserIdDiaryLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedProfileUserIdDiaryLayoutRoute,
  } as any)

const LayoutProtectedProfileUserIdCropStorageLayoutIndexRoute =
  LayoutProtectedProfileUserIdCropStorageLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedProfileUserIdCropStorageLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_protected': {
      id: '/_layout/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutProtectedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_protected/_home': {
      id: '/_layout/_protected/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutProtectedHomeImport
      parentRoute: typeof LayoutProtectedImport
    }
    '/_layout/signup': {
      id: '/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/_layout': {
      id: '/_layout/signup/_layout'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupLayoutImport
      parentRoute: typeof LayoutSignupRoute
    }
    '/_layout/login/': {
      id: '/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/signup/': {
      id: '/_layout/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof LayoutSignupIndexImport
      parentRoute: typeof LayoutSignupImport
    }
    '/_layout/_protected/community': {
      id: '/_layout/_protected/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof LayoutProtectedCommunityImport
      parentRoute: typeof LayoutProtectedImport
    }
    '/_layout/_protected/community/_layout': {
      id: '/_layout/_protected/community/_layout'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof LayoutProtectedCommunityLayoutImport
      parentRoute: typeof LayoutProtectedCommunityRoute
    }
    '/_layout/_protected/diary': {
      id: '/_layout/_protected/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof LayoutProtectedDiaryImport
      parentRoute: typeof LayoutProtectedImport
    }
    '/_layout/_protected/diary/_layout': {
      id: '/_layout/_protected/diary/_layout'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof LayoutProtectedDiaryLayoutImport
      parentRoute: typeof LayoutProtectedDiaryRoute
    }
    '/_layout/_protected/profile': {
      id: '/_layout/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProtectedProfileImport
      parentRoute: typeof LayoutProtectedImport
    }
    '/_layout/_protected/profile/_layout': {
      id: '/_layout/_protected/profile/_layout'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProtectedProfileLayoutImport
      parentRoute: typeof LayoutProtectedProfileRoute
    }
    '/_layout/_protected/trade': {
      id: '/_layout/_protected/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof LayoutProtectedTradeImport
      parentRoute: typeof LayoutProtectedImport
    }
    '/_layout/_protected/trade/_layout': {
      id: '/_layout/_protected/trade/_layout'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof LayoutProtectedTradeLayoutImport
      parentRoute: typeof LayoutProtectedTradeRoute
    }
    '/_layout/signup/_layout/1': {
      id: '/_layout/signup/_layout/1'
      path: '/1'
      fullPath: '/signup/1'
      preLoaderRoute: typeof LayoutSignupLayout1Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/2': {
      id: '/_layout/signup/_layout/2'
      path: '/2'
      fullPath: '/signup/2'
      preLoaderRoute: typeof LayoutSignupLayout2Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/3': {
      id: '/_layout/signup/_layout/3'
      path: '/3'
      fullPath: '/signup/3'
      preLoaderRoute: typeof LayoutSignupLayout3Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/4': {
      id: '/_layout/signup/_layout/4'
      path: '/4'
      fullPath: '/signup/4'
      preLoaderRoute: typeof LayoutSignupLayout4Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/5': {
      id: '/_layout/signup/_layout/5'
      path: '/5'
      fullPath: '/signup/5'
      preLoaderRoute: typeof LayoutSignupLayout5Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/6': {
      id: '/_layout/signup/_layout/6'
      path: '/6'
      fullPath: '/signup/6'
      preLoaderRoute: typeof LayoutSignupLayout6Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/7': {
      id: '/_layout/signup/_layout/7'
      path: '/7'
      fullPath: '/signup/7'
      preLoaderRoute: typeof LayoutSignupLayout7Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/8': {
      id: '/_layout/signup/_layout/8'
      path: '/8'
      fullPath: '/signup/8'
      preLoaderRoute: typeof LayoutSignupLayout8Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/9': {
      id: '/_layout/signup/_layout/9'
      path: '/9'
      fullPath: '/signup/9'
      preLoaderRoute: typeof LayoutSignupLayout9Import
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/signup/_layout/additional': {
      id: '/_layout/signup/_layout/additional'
      path: '/additional'
      fullPath: '/signup/additional'
      preLoaderRoute: typeof LayoutSignupLayoutAdditionalImport
      parentRoute: typeof LayoutSignupLayoutImport
    }
    '/_layout/_protected/_home/': {
      id: '/_layout/_protected/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutProtectedHomeIndexImport
      parentRoute: typeof LayoutProtectedHomeImport
    }
    '/_layout/_protected/search/': {
      id: '/_layout/_protected/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutProtectedSearchIndexImport
      parentRoute: typeof LayoutProtectedImport
    }
    '/_layout/login/entrance/': {
      id: '/_layout/login/entrance/'
      path: '/login/entrance'
      fullPath: '/login/entrance'
      preLoaderRoute: typeof LayoutLoginEntranceIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_protected/community/detail': {
      id: '/_layout/_protected/community/detail'
      path: '/detail'
      fullPath: '/community/detail'
      preLoaderRoute: typeof LayoutProtectedCommunityDetailImport
      parentRoute: typeof LayoutProtectedCommunityImport
    }
    '/_layout/_protected/community/detail/_layout': {
      id: '/_layout/_protected/community/detail/_layout'
      path: '/detail'
      fullPath: '/community/detail'
      preLoaderRoute: typeof LayoutProtectedCommunityDetailLayoutImport
      parentRoute: typeof LayoutProtectedCommunityDetailRoute
    }
    '/_layout/_protected/diary/detail': {
      id: '/_layout/_protected/diary/detail'
      path: '/detail'
      fullPath: '/diary/detail'
      preLoaderRoute: typeof LayoutProtectedDiaryDetailImport
      parentRoute: typeof LayoutProtectedDiaryImport
    }
    '/_layout/_protected/diary/detail/_layout': {
      id: '/_layout/_protected/diary/detail/_layout'
      path: '/detail'
      fullPath: '/diary/detail'
      preLoaderRoute: typeof LayoutProtectedDiaryDetailLayoutImport
      parentRoute: typeof LayoutProtectedDiaryDetailRoute
    }
    '/_layout/_protected/diary/growDiary': {
      id: '/_layout/_protected/diary/growDiary'
      path: '/growDiary'
      fullPath: '/diary/growDiary'
      preLoaderRoute: typeof LayoutProtectedDiaryGrowDiaryImport
      parentRoute: typeof LayoutProtectedDiaryImport
    }
    '/_layout/_protected/diary/growDiary/_layout': {
      id: '/_layout/_protected/diary/growDiary/_layout'
      path: '/growDiary'
      fullPath: '/diary/growDiary'
      preLoaderRoute: typeof LayoutProtectedDiaryGrowDiaryLayoutImport
      parentRoute: typeof LayoutProtectedDiaryGrowDiaryRoute
    }
    '/_layout/_protected/diary/registerCrop': {
      id: '/_layout/_protected/diary/registerCrop'
      path: '/registerCrop'
      fullPath: '/diary/registerCrop'
      preLoaderRoute: typeof LayoutProtectedDiaryRegisterCropImport
      parentRoute: typeof LayoutProtectedDiaryImport
    }
    '/_layout/_protected/diary/registerCrop/_layout': {
      id: '/_layout/_protected/diary/registerCrop/_layout'
      path: '/registerCrop'
      fullPath: '/diary/registerCrop'
      preLoaderRoute: typeof LayoutProtectedDiaryRegisterCropLayoutImport
      parentRoute: typeof LayoutProtectedDiaryRegisterCropRoute
    }
    '/_layout/_protected/diary/write': {
      id: '/_layout/_protected/diary/write'
      path: '/write'
      fullPath: '/diary/write'
      preLoaderRoute: typeof LayoutProtectedDiaryWriteImport
      parentRoute: typeof LayoutProtectedDiaryImport
    }
    '/_layout/_protected/diary/write/_layout': {
      id: '/_layout/_protected/diary/write/_layout'
      path: '/write'
      fullPath: '/diary/write'
      preLoaderRoute: typeof LayoutProtectedDiaryWriteLayoutImport
      parentRoute: typeof LayoutProtectedDiaryWriteRoute
    }
    '/_layout/_protected/profile/$userId': {
      id: '/_layout/_protected/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdImport
      parentRoute: typeof LayoutProtectedProfileImport
    }
    '/_layout/_protected/profile/$userId/_layout': {
      id: '/_layout/_protected/profile/$userId/_layout'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdLayoutImport
      parentRoute: typeof LayoutProtectedProfileUserIdRoute
    }
    '/_layout/_protected/profile/changelocation': {
      id: '/_layout/_protected/profile/changelocation'
      path: '/changelocation'
      fullPath: '/profile/changelocation'
      preLoaderRoute: typeof LayoutProtectedProfileChangelocationImport
      parentRoute: typeof LayoutProtectedProfileImport
    }
    '/_layout/_protected/profile/changelocation/_layout': {
      id: '/_layout/_protected/profile/changelocation/_layout'
      path: '/changelocation'
      fullPath: '/profile/changelocation'
      preLoaderRoute: typeof LayoutProtectedProfileChangelocationLayoutImport
      parentRoute: typeof LayoutProtectedProfileChangelocationRoute
    }
    '/_layout/_protected/profile/chat': {
      id: '/_layout/_protected/profile/chat'
      path: '/chat'
      fullPath: '/profile/chat'
      preLoaderRoute: typeof LayoutProtectedProfileChatImport
      parentRoute: typeof LayoutProtectedProfileImport
    }
    '/_layout/_protected/profile/chat/_layout': {
      id: '/_layout/_protected/profile/chat/_layout'
      path: '/chat'
      fullPath: '/profile/chat'
      preLoaderRoute: typeof LayoutProtectedProfileChatLayoutImport
      parentRoute: typeof LayoutProtectedProfileChatRoute
    }
    '/_layout/_protected/profile/picked': {
      id: '/_layout/_protected/profile/picked'
      path: '/picked'
      fullPath: '/profile/picked'
      preLoaderRoute: typeof LayoutProtectedProfilePickedImport
      parentRoute: typeof LayoutProtectedProfileImport
    }
    '/_layout/_protected/profile/picked/_layout': {
      id: '/_layout/_protected/profile/picked/_layout'
      path: '/picked'
      fullPath: '/profile/picked'
      preLoaderRoute: typeof LayoutProtectedProfilePickedLayoutImport
      parentRoute: typeof LayoutProtectedProfilePickedRoute
    }
    '/_layout/_protected/profile/writed': {
      id: '/_layout/_protected/profile/writed'
      path: '/writed'
      fullPath: '/profile/writed'
      preLoaderRoute: typeof LayoutProtectedProfileWritedImport
      parentRoute: typeof LayoutProtectedProfileImport
    }
    '/_layout/_protected/profile/writed/_layout': {
      id: '/_layout/_protected/profile/writed/_layout'
      path: '/writed'
      fullPath: '/profile/writed'
      preLoaderRoute: typeof LayoutProtectedProfileWritedLayoutImport
      parentRoute: typeof LayoutProtectedProfileWritedRoute
    }
    '/_layout/_protected/search/$result': {
      id: '/_layout/_protected/search/$result'
      path: '/search/$result'
      fullPath: '/search/$result'
      preLoaderRoute: typeof LayoutProtectedSearchResultImport
      parentRoute: typeof LayoutProtectedImport
    }
    '/_layout/_protected/search/$result/_layout': {
      id: '/_layout/_protected/search/$result/_layout'
      path: '/search/$result'
      fullPath: '/search/$result'
      preLoaderRoute: typeof LayoutProtectedSearchResultLayoutImport
      parentRoute: typeof LayoutProtectedSearchResultRoute
    }
    '/_layout/_protected/trade/detail': {
      id: '/_layout/_protected/trade/detail'
      path: '/detail'
      fullPath: '/trade/detail'
      preLoaderRoute: typeof LayoutProtectedTradeDetailImport
      parentRoute: typeof LayoutProtectedTradeImport
    }
    '/_layout/_protected/trade/detail/_layout': {
      id: '/_layout/_protected/trade/detail/_layout'
      path: '/detail'
      fullPath: '/trade/detail'
      preLoaderRoute: typeof LayoutProtectedTradeDetailLayoutImport
      parentRoute: typeof LayoutProtectedTradeDetailRoute
    }
    '/_layout/_protected/trade/from': {
      id: '/_layout/_protected/trade/from'
      path: '/from'
      fullPath: '/trade/from'
      preLoaderRoute: typeof LayoutProtectedTradeFromImport
      parentRoute: typeof LayoutProtectedTradeImport
    }
    '/_layout/_protected/trade/from/_layout': {
      id: '/_layout/_protected/trade/from/_layout'
      path: '/from'
      fullPath: '/trade/from'
      preLoaderRoute: typeof LayoutProtectedTradeFromLayoutImport
      parentRoute: typeof LayoutProtectedTradeFromRoute
    }
    '/_layout/_protected/trade/to': {
      id: '/_layout/_protected/trade/to'
      path: '/to'
      fullPath: '/trade/to'
      preLoaderRoute: typeof LayoutProtectedTradeToImport
      parentRoute: typeof LayoutProtectedTradeImport
    }
    '/_layout/_protected/trade/to/_layout': {
      id: '/_layout/_protected/trade/to/_layout'
      path: '/to'
      fullPath: '/trade/to'
      preLoaderRoute: typeof LayoutProtectedTradeToLayoutImport
      parentRoute: typeof LayoutProtectedTradeToRoute
    }
    '/_layout/_protected/trade/write': {
      id: '/_layout/_protected/trade/write'
      path: '/write'
      fullPath: '/trade/write'
      preLoaderRoute: typeof LayoutProtectedTradeWriteImport
      parentRoute: typeof LayoutProtectedTradeImport
    }
    '/_layout/_protected/trade/write/_layout': {
      id: '/_layout/_protected/trade/write/_layout'
      path: '/write'
      fullPath: '/trade/write'
      preLoaderRoute: typeof LayoutProtectedTradeWriteLayoutImport
      parentRoute: typeof LayoutProtectedTradeWriteRoute
    }
    '/_layout/_protected/community/_layout/': {
      id: '/_layout/_protected/community/_layout/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof LayoutProtectedCommunityLayoutIndexImport
      parentRoute: typeof LayoutProtectedCommunityLayoutImport
    }
    '/_layout/_protected/community/create/': {
      id: '/_layout/_protected/community/create/'
      path: '/create'
      fullPath: '/community/create'
      preLoaderRoute: typeof LayoutProtectedCommunityCreateIndexImport
      parentRoute: typeof LayoutProtectedCommunityImport
    }
    '/_layout/_protected/diary/_layout/': {
      id: '/_layout/_protected/diary/_layout/'
      path: '/'
      fullPath: '/diary/'
      preLoaderRoute: typeof LayoutProtectedDiaryLayoutIndexImport
      parentRoute: typeof LayoutProtectedDiaryLayoutImport
    }
    '/_layout/_protected/diary/registerCrop/': {
      id: '/_layout/_protected/diary/registerCrop/'
      path: '/'
      fullPath: '/diary/registerCrop/'
      preLoaderRoute: typeof LayoutProtectedDiaryRegisterCropIndexImport
      parentRoute: typeof LayoutProtectedDiaryRegisterCropImport
    }
    '/_layout/_protected/diary/write/': {
      id: '/_layout/_protected/diary/write/'
      path: '/'
      fullPath: '/diary/write/'
      preLoaderRoute: typeof LayoutProtectedDiaryWriteIndexImport
      parentRoute: typeof LayoutProtectedDiaryWriteImport
    }
    '/_layout/_protected/profile/_layout/': {
      id: '/_layout/_protected/profile/_layout/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutProtectedProfileLayoutIndexImport
      parentRoute: typeof LayoutProtectedProfileLayoutImport
    }
    '/_layout/_protected/profile/aireport/': {
      id: '/_layout/_protected/profile/aireport/'
      path: '/aireport'
      fullPath: '/profile/aireport'
      preLoaderRoute: typeof LayoutProtectedProfileAireportIndexImport
      parentRoute: typeof LayoutProtectedProfileImport
    }
    '/_layout/_protected/trade/_layout/': {
      id: '/_layout/_protected/trade/_layout/'
      path: '/'
      fullPath: '/trade/'
      preLoaderRoute: typeof LayoutProtectedTradeLayoutIndexImport
      parentRoute: typeof LayoutProtectedTradeLayoutImport
    }
    '/_layout/_protected/community/detail/_layout/$postId': {
      id: '/_layout/_protected/community/detail/_layout/$postId'
      path: '/$postId'
      fullPath: '/community/detail/$postId'
      preLoaderRoute: typeof LayoutProtectedCommunityDetailLayoutPostIdImport
      parentRoute: typeof LayoutProtectedCommunityDetailLayoutImport
    }
    '/_layout/_protected/diary/detail/_layout/$cropDiaryId': {
      id: '/_layout/_protected/diary/detail/_layout/$cropDiaryId'
      path: '/$cropDiaryId'
      fullPath: '/diary/detail/$cropDiaryId'
      preLoaderRoute: typeof LayoutProtectedDiaryDetailLayoutCropDiaryIdImport
      parentRoute: typeof LayoutProtectedDiaryDetailLayoutImport
    }
    '/_layout/_protected/diary/growDiary/_layout/$cropId': {
      id: '/_layout/_protected/diary/growDiary/_layout/$cropId'
      path: '/$cropId'
      fullPath: '/diary/growDiary/$cropId'
      preLoaderRoute: typeof LayoutProtectedDiaryGrowDiaryLayoutCropIdImport
      parentRoute: typeof LayoutProtectedDiaryGrowDiaryLayoutImport
    }
    '/_layout/_protected/diary/registerCrop/_layout/1': {
      id: '/_layout/_protected/diary/registerCrop/_layout/1'
      path: '/1'
      fullPath: '/diary/registerCrop/1'
      preLoaderRoute: typeof LayoutProtectedDiaryRegisterCropLayout1Import
      parentRoute: typeof LayoutProtectedDiaryRegisterCropLayoutImport
    }
    '/_layout/_protected/diary/registerCrop/_layout/2': {
      id: '/_layout/_protected/diary/registerCrop/_layout/2'
      path: '/2'
      fullPath: '/diary/registerCrop/2'
      preLoaderRoute: typeof LayoutProtectedDiaryRegisterCropLayout2Import
      parentRoute: typeof LayoutProtectedDiaryRegisterCropLayoutImport
    }
    '/_layout/_protected/diary/registerCrop/_layout/3': {
      id: '/_layout/_protected/diary/registerCrop/_layout/3'
      path: '/3'
      fullPath: '/diary/registerCrop/3'
      preLoaderRoute: typeof LayoutProtectedDiaryRegisterCropLayout3Import
      parentRoute: typeof LayoutProtectedDiaryRegisterCropLayoutImport
    }
    '/_layout/_protected/diary/registerCrop/_layout/4': {
      id: '/_layout/_protected/diary/registerCrop/_layout/4'
      path: '/4'
      fullPath: '/diary/registerCrop/4'
      preLoaderRoute: typeof LayoutProtectedDiaryRegisterCropLayout4Import
      parentRoute: typeof LayoutProtectedDiaryRegisterCropLayoutImport
    }
    '/_layout/_protected/diary/registerCrop/_layout/5': {
      id: '/_layout/_protected/diary/registerCrop/_layout/5'
      path: '/5'
      fullPath: '/diary/registerCrop/5'
      preLoaderRoute: typeof LayoutProtectedDiaryRegisterCropLayout5Import
      parentRoute: typeof LayoutProtectedDiaryRegisterCropLayoutImport
    }
    '/_layout/_protected/diary/write/_layout/1': {
      id: '/_layout/_protected/diary/write/_layout/1'
      path: '/1'
      fullPath: '/diary/write/1'
      preLoaderRoute: typeof LayoutProtectedDiaryWriteLayout1Import
      parentRoute: typeof LayoutProtectedDiaryWriteLayoutImport
    }
    '/_layout/_protected/diary/write/_layout/2': {
      id: '/_layout/_protected/diary/write/_layout/2'
      path: '/2'
      fullPath: '/diary/write/2'
      preLoaderRoute: typeof LayoutProtectedDiaryWriteLayout2Import
      parentRoute: typeof LayoutProtectedDiaryWriteLayoutImport
    }
    '/_layout/_protected/profile/$userId/cropStorage': {
      id: '/_layout/_protected/profile/$userId/cropStorage'
      path: '/cropStorage'
      fullPath: '/profile/$userId/cropStorage'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdCropStorageImport
      parentRoute: typeof LayoutProtectedProfileUserIdImport
    }
    '/_layout/_protected/profile/$userId/cropStorage/_layout': {
      id: '/_layout/_protected/profile/$userId/cropStorage/_layout'
      path: '/cropStorage'
      fullPath: '/profile/$userId/cropStorage'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdCropStorageLayoutImport
      parentRoute: typeof LayoutProtectedProfileUserIdCropStorageRoute
    }
    '/_layout/_protected/profile/$userId/diary': {
      id: '/_layout/_protected/profile/$userId/diary'
      path: '/diary'
      fullPath: '/profile/$userId/diary'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdDiaryImport
      parentRoute: typeof LayoutProtectedProfileUserIdImport
    }
    '/_layout/_protected/profile/$userId/diary/_layout': {
      id: '/_layout/_protected/profile/$userId/diary/_layout'
      path: '/diary'
      fullPath: '/profile/$userId/diary'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdDiaryLayoutImport
      parentRoute: typeof LayoutProtectedProfileUserIdDiaryRoute
    }
    '/_layout/_protected/profile/aireport/detail/$reportId': {
      id: '/_layout/_protected/profile/aireport/detail/$reportId'
      path: '/aireport/detail/$reportId'
      fullPath: '/profile/aireport/detail/$reportId'
      preLoaderRoute: typeof LayoutProtectedProfileAireportDetailReportIdImport
      parentRoute: typeof LayoutProtectedProfileImport
    }
    '/_layout/_protected/trade/detail/_layout/$tradeId': {
      id: '/_layout/_protected/trade/detail/_layout/$tradeId'
      path: '/$tradeId'
      fullPath: '/trade/detail/$tradeId'
      preLoaderRoute: typeof LayoutProtectedTradeDetailLayoutTradeIdImport
      parentRoute: typeof LayoutProtectedTradeDetailLayoutImport
    }
    '/_layout/_protected/profile/$userId/_layout/': {
      id: '/_layout/_protected/profile/$userId/_layout/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdLayoutIndexImport
      parentRoute: typeof LayoutProtectedProfileUserIdLayoutImport
    }
    '/_layout/_protected/profile/changelocation/_layout/': {
      id: '/_layout/_protected/profile/changelocation/_layout/'
      path: '/'
      fullPath: '/profile/changelocation/'
      preLoaderRoute: typeof LayoutProtectedProfileChangelocationLayoutIndexImport
      parentRoute: typeof LayoutProtectedProfileChangelocationLayoutImport
    }
    '/_layout/_protected/profile/chat/_layout/': {
      id: '/_layout/_protected/profile/chat/_layout/'
      path: '/'
      fullPath: '/profile/chat/'
      preLoaderRoute: typeof LayoutProtectedProfileChatLayoutIndexImport
      parentRoute: typeof LayoutProtectedProfileChatLayoutImport
    }
    '/_layout/_protected/profile/picked/_layout/': {
      id: '/_layout/_protected/profile/picked/_layout/'
      path: '/'
      fullPath: '/profile/picked/'
      preLoaderRoute: typeof LayoutProtectedProfilePickedLayoutIndexImport
      parentRoute: typeof LayoutProtectedProfilePickedLayoutImport
    }
    '/_layout/_protected/profile/writed/_layout/': {
      id: '/_layout/_protected/profile/writed/_layout/'
      path: '/'
      fullPath: '/profile/writed/'
      preLoaderRoute: typeof LayoutProtectedProfileWritedLayoutIndexImport
      parentRoute: typeof LayoutProtectedProfileWritedLayoutImport
    }
    '/_layout/_protected/search/$result/_layout/': {
      id: '/_layout/_protected/search/$result/_layout/'
      path: '/'
      fullPath: '/search/$result/'
      preLoaderRoute: typeof LayoutProtectedSearchResultLayoutIndexImport
      parentRoute: typeof LayoutProtectedSearchResultLayoutImport
    }
    '/_layout/_protected/trade/from/_layout/': {
      id: '/_layout/_protected/trade/from/_layout/'
      path: '/'
      fullPath: '/trade/from/'
      preLoaderRoute: typeof LayoutProtectedTradeFromLayoutIndexImport
      parentRoute: typeof LayoutProtectedTradeFromLayoutImport
    }
    '/_layout/_protected/trade/to/_layout/': {
      id: '/_layout/_protected/trade/to/_layout/'
      path: '/'
      fullPath: '/trade/to/'
      preLoaderRoute: typeof LayoutProtectedTradeToLayoutIndexImport
      parentRoute: typeof LayoutProtectedTradeToLayoutImport
    }
    '/_layout/_protected/trade/write/_layout/': {
      id: '/_layout/_protected/trade/write/_layout/'
      path: '/'
      fullPath: '/trade/write/'
      preLoaderRoute: typeof LayoutProtectedTradeWriteLayoutIndexImport
      parentRoute: typeof LayoutProtectedTradeWriteLayoutImport
    }
    '/_layout/_protected/profile/$userId/cropStorage/_layout/': {
      id: '/_layout/_protected/profile/$userId/cropStorage/_layout/'
      path: '/'
      fullPath: '/profile/$userId/cropStorage/'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdCropStorageLayoutIndexImport
      parentRoute: typeof LayoutProtectedProfileUserIdCropStorageLayoutImport
    }
    '/_layout/_protected/profile/$userId/diary/_layout/': {
      id: '/_layout/_protected/profile/$userId/diary/_layout/'
      path: '/'
      fullPath: '/profile/$userId/diary/'
      preLoaderRoute: typeof LayoutProtectedProfileUserIdDiaryLayoutIndexImport
      parentRoute: typeof LayoutProtectedProfileUserIdDiaryLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutProtectedRoute: LayoutProtectedRoute.addChildren({
      LayoutProtectedHomeRoute: LayoutProtectedHomeRoute.addChildren({
        LayoutProtectedHomeIndexRoute,
      }),
      LayoutProtectedCommunityRoute: LayoutProtectedCommunityRoute.addChildren({
        LayoutProtectedCommunityLayoutRoute:
          LayoutProtectedCommunityLayoutRoute.addChildren({
            LayoutProtectedCommunityLayoutIndexRoute,
          }),
        LayoutProtectedCommunityDetailRoute:
          LayoutProtectedCommunityDetailRoute.addChildren({
            LayoutProtectedCommunityDetailLayoutRoute:
              LayoutProtectedCommunityDetailLayoutRoute.addChildren({
                LayoutProtectedCommunityDetailLayoutPostIdRoute,
              }),
          }),
        LayoutProtectedCommunityCreateIndexRoute,
      }),
      LayoutProtectedDiaryRoute: LayoutProtectedDiaryRoute.addChildren({
        LayoutProtectedDiaryLayoutRoute:
          LayoutProtectedDiaryLayoutRoute.addChildren({
            LayoutProtectedDiaryLayoutIndexRoute,
          }),
        LayoutProtectedDiaryDetailRoute:
          LayoutProtectedDiaryDetailRoute.addChildren({
            LayoutProtectedDiaryDetailLayoutRoute:
              LayoutProtectedDiaryDetailLayoutRoute.addChildren({
                LayoutProtectedDiaryDetailLayoutCropDiaryIdRoute,
              }),
          }),
        LayoutProtectedDiaryGrowDiaryRoute:
          LayoutProtectedDiaryGrowDiaryRoute.addChildren({
            LayoutProtectedDiaryGrowDiaryLayoutRoute:
              LayoutProtectedDiaryGrowDiaryLayoutRoute.addChildren({
                LayoutProtectedDiaryGrowDiaryLayoutCropIdRoute,
              }),
          }),
        LayoutProtectedDiaryRegisterCropRoute:
          LayoutProtectedDiaryRegisterCropRoute.addChildren({
            LayoutProtectedDiaryRegisterCropLayoutRoute:
              LayoutProtectedDiaryRegisterCropLayoutRoute.addChildren({
                LayoutProtectedDiaryRegisterCropLayout1Route,
                LayoutProtectedDiaryRegisterCropLayout2Route,
                LayoutProtectedDiaryRegisterCropLayout3Route,
                LayoutProtectedDiaryRegisterCropLayout4Route,
                LayoutProtectedDiaryRegisterCropLayout5Route,
              }),
            LayoutProtectedDiaryRegisterCropIndexRoute,
          }),
        LayoutProtectedDiaryWriteRoute:
          LayoutProtectedDiaryWriteRoute.addChildren({
            LayoutProtectedDiaryWriteLayoutRoute:
              LayoutProtectedDiaryWriteLayoutRoute.addChildren({
                LayoutProtectedDiaryWriteLayout1Route,
                LayoutProtectedDiaryWriteLayout2Route,
              }),
            LayoutProtectedDiaryWriteIndexRoute,
          }),
      }),
      LayoutProtectedProfileRoute: LayoutProtectedProfileRoute.addChildren({
        LayoutProtectedProfileLayoutRoute:
          LayoutProtectedProfileLayoutRoute.addChildren({
            LayoutProtectedProfileLayoutIndexRoute,
          }),
        LayoutProtectedProfileUserIdRoute:
          LayoutProtectedProfileUserIdRoute.addChildren({
            LayoutProtectedProfileUserIdLayoutRoute:
              LayoutProtectedProfileUserIdLayoutRoute.addChildren({
                LayoutProtectedProfileUserIdLayoutIndexRoute,
              }),
            LayoutProtectedProfileUserIdCropStorageRoute:
              LayoutProtectedProfileUserIdCropStorageRoute.addChildren({
                LayoutProtectedProfileUserIdCropStorageLayoutRoute:
                  LayoutProtectedProfileUserIdCropStorageLayoutRoute.addChildren(
                    { LayoutProtectedProfileUserIdCropStorageLayoutIndexRoute },
                  ),
              }),
            LayoutProtectedProfileUserIdDiaryRoute:
              LayoutProtectedProfileUserIdDiaryRoute.addChildren({
                LayoutProtectedProfileUserIdDiaryLayoutRoute:
                  LayoutProtectedProfileUserIdDiaryLayoutRoute.addChildren({
                    LayoutProtectedProfileUserIdDiaryLayoutIndexRoute,
                  }),
              }),
          }),
        LayoutProtectedProfileChangelocationRoute:
          LayoutProtectedProfileChangelocationRoute.addChildren({
            LayoutProtectedProfileChangelocationLayoutRoute:
              LayoutProtectedProfileChangelocationLayoutRoute.addChildren({
                LayoutProtectedProfileChangelocationLayoutIndexRoute,
              }),
          }),
        LayoutProtectedProfileChatRoute:
          LayoutProtectedProfileChatRoute.addChildren({
            LayoutProtectedProfileChatLayoutRoute:
              LayoutProtectedProfileChatLayoutRoute.addChildren({
                LayoutProtectedProfileChatLayoutIndexRoute,
              }),
          }),
        LayoutProtectedProfilePickedRoute:
          LayoutProtectedProfilePickedRoute.addChildren({
            LayoutProtectedProfilePickedLayoutRoute:
              LayoutProtectedProfilePickedLayoutRoute.addChildren({
                LayoutProtectedProfilePickedLayoutIndexRoute,
              }),
          }),
        LayoutProtectedProfileWritedRoute:
          LayoutProtectedProfileWritedRoute.addChildren({
            LayoutProtectedProfileWritedLayoutRoute:
              LayoutProtectedProfileWritedLayoutRoute.addChildren({
                LayoutProtectedProfileWritedLayoutIndexRoute,
              }),
          }),
        LayoutProtectedProfileAireportIndexRoute,
        LayoutProtectedProfileAireportDetailReportIdRoute,
      }),
      LayoutProtectedTradeRoute: LayoutProtectedTradeRoute.addChildren({
        LayoutProtectedTradeLayoutRoute:
          LayoutProtectedTradeLayoutRoute.addChildren({
            LayoutProtectedTradeLayoutIndexRoute,
          }),
        LayoutProtectedTradeDetailRoute:
          LayoutProtectedTradeDetailRoute.addChildren({
            LayoutProtectedTradeDetailLayoutRoute:
              LayoutProtectedTradeDetailLayoutRoute.addChildren({
                LayoutProtectedTradeDetailLayoutTradeIdRoute,
              }),
          }),
        LayoutProtectedTradeFromRoute:
          LayoutProtectedTradeFromRoute.addChildren({
            LayoutProtectedTradeFromLayoutRoute:
              LayoutProtectedTradeFromLayoutRoute.addChildren({
                LayoutProtectedTradeFromLayoutIndexRoute,
              }),
          }),
        LayoutProtectedTradeToRoute: LayoutProtectedTradeToRoute.addChildren({
          LayoutProtectedTradeToLayoutRoute:
            LayoutProtectedTradeToLayoutRoute.addChildren({
              LayoutProtectedTradeToLayoutIndexRoute,
            }),
        }),
        LayoutProtectedTradeWriteRoute:
          LayoutProtectedTradeWriteRoute.addChildren({
            LayoutProtectedTradeWriteLayoutRoute:
              LayoutProtectedTradeWriteLayoutRoute.addChildren({
                LayoutProtectedTradeWriteLayoutIndexRoute,
              }),
          }),
      }),
      LayoutProtectedSearchIndexRoute,
      LayoutProtectedSearchResultRoute:
        LayoutProtectedSearchResultRoute.addChildren({
          LayoutProtectedSearchResultLayoutRoute:
            LayoutProtectedSearchResultLayoutRoute.addChildren({
              LayoutProtectedSearchResultLayoutIndexRoute,
            }),
        }),
    }),
    LayoutSignupRoute: LayoutSignupRoute.addChildren({
      LayoutSignupLayoutRoute: LayoutSignupLayoutRoute.addChildren({
        LayoutSignupLayout1Route,
        LayoutSignupLayout2Route,
        LayoutSignupLayout3Route,
        LayoutSignupLayout4Route,
        LayoutSignupLayout5Route,
        LayoutSignupLayout6Route,
        LayoutSignupLayout7Route,
        LayoutSignupLayout8Route,
        LayoutSignupLayout9Route,
        LayoutSignupLayoutAdditionalRoute,
      }),
      LayoutSignupIndexRoute,
    }),
    LayoutLoginIndexRoute,
    LayoutLoginEntranceIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_protected",
        "/_layout/signup",
        "/_layout/login/",
        "/_layout/login/entrance/"
      ]
    },
    "/_layout/_protected": {
      "filePath": "_layout/_protected.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_protected/_home",
        "/_layout/_protected/community",
        "/_layout/_protected/diary",
        "/_layout/_protected/profile",
        "/_layout/_protected/trade",
        "/_layout/_protected/search/",
        "/_layout/_protected/search/$result"
      ]
    },
    "/_layout/_protected/_home": {
      "filePath": "_layout/_protected/_home.tsx",
      "parent": "/_layout/_protected",
      "children": [
        "/_layout/_protected/_home/"
      ]
    },
    "/_layout/signup": {
      "filePath": "_layout/signup",
      "parent": "/_layout",
      "children": [
        "/_layout/signup/_layout",
        "/_layout/signup/"
      ]
    },
    "/_layout/signup/_layout": {
      "filePath": "_layout/signup/_layout.tsx",
      "parent": "/_layout/signup",
      "children": [
        "/_layout/signup/_layout/1",
        "/_layout/signup/_layout/2",
        "/_layout/signup/_layout/3",
        "/_layout/signup/_layout/4",
        "/_layout/signup/_layout/5",
        "/_layout/signup/_layout/6",
        "/_layout/signup/_layout/7",
        "/_layout/signup/_layout/8",
        "/_layout/signup/_layout/9",
        "/_layout/signup/_layout/additional"
      ]
    },
    "/_layout/login/": {
      "filePath": "_layout/login/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/signup/": {
      "filePath": "_layout/signup/index.tsx",
      "parent": "/_layout/signup"
    },
    "/_layout/_protected/community": {
      "filePath": "_layout/_protected/community",
      "parent": "/_layout/_protected",
      "children": [
        "/_layout/_protected/community/_layout",
        "/_layout/_protected/community/detail",
        "/_layout/_protected/community/create/"
      ]
    },
    "/_layout/_protected/community/_layout": {
      "filePath": "_layout/_protected/community/_layout.tsx",
      "parent": "/_layout/_protected/community",
      "children": [
        "/_layout/_protected/community/_layout/"
      ]
    },
    "/_layout/_protected/diary": {
      "filePath": "_layout/_protected/diary",
      "parent": "/_layout/_protected",
      "children": [
        "/_layout/_protected/diary/_layout",
        "/_layout/_protected/diary/detail",
        "/_layout/_protected/diary/growDiary",
        "/_layout/_protected/diary/registerCrop",
        "/_layout/_protected/diary/write"
      ]
    },
    "/_layout/_protected/diary/_layout": {
      "filePath": "_layout/_protected/diary/_layout.tsx",
      "parent": "/_layout/_protected/diary",
      "children": [
        "/_layout/_protected/diary/_layout/"
      ]
    },
    "/_layout/_protected/profile": {
      "filePath": "_layout/_protected/profile",
      "parent": "/_layout/_protected",
      "children": [
        "/_layout/_protected/profile/_layout",
        "/_layout/_protected/profile/$userId",
        "/_layout/_protected/profile/changelocation",
        "/_layout/_protected/profile/chat",
        "/_layout/_protected/profile/picked",
        "/_layout/_protected/profile/writed",
        "/_layout/_protected/profile/aireport/",
        "/_layout/_protected/profile/aireport/detail/$reportId"
      ]
    },
    "/_layout/_protected/profile/_layout": {
      "filePath": "_layout/_protected/profile/_layout.tsx",
      "parent": "/_layout/_protected/profile",
      "children": [
        "/_layout/_protected/profile/_layout/"
      ]
    },
    "/_layout/_protected/trade": {
      "filePath": "_layout/_protected/trade",
      "parent": "/_layout/_protected",
      "children": [
        "/_layout/_protected/trade/_layout",
        "/_layout/_protected/trade/detail",
        "/_layout/_protected/trade/from",
        "/_layout/_protected/trade/to",
        "/_layout/_protected/trade/write"
      ]
    },
    "/_layout/_protected/trade/_layout": {
      "filePath": "_layout/_protected/trade/_layout.tsx",
      "parent": "/_layout/_protected/trade",
      "children": [
        "/_layout/_protected/trade/_layout/"
      ]
    },
    "/_layout/signup/_layout/1": {
      "filePath": "_layout/signup/_layout/1.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/2": {
      "filePath": "_layout/signup/_layout/2.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/3": {
      "filePath": "_layout/signup/_layout/3.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/4": {
      "filePath": "_layout/signup/_layout/4.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/5": {
      "filePath": "_layout/signup/_layout/5.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/6": {
      "filePath": "_layout/signup/_layout/6.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/7": {
      "filePath": "_layout/signup/_layout/7.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/8": {
      "filePath": "_layout/signup/_layout/8.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/9": {
      "filePath": "_layout/signup/_layout/9.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/signup/_layout/additional": {
      "filePath": "_layout/signup/_layout/additional.tsx",
      "parent": "/_layout/signup/_layout"
    },
    "/_layout/_protected/_home/": {
      "filePath": "_layout/_protected/_home/index.tsx",
      "parent": "/_layout/_protected/_home"
    },
    "/_layout/_protected/search/": {
      "filePath": "_layout/_protected/search/index.tsx",
      "parent": "/_layout/_protected"
    },
    "/_layout/login/entrance/": {
      "filePath": "_layout/login/entrance/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_protected/community/detail": {
      "filePath": "_layout/_protected/community/detail",
      "parent": "/_layout/_protected/community",
      "children": [
        "/_layout/_protected/community/detail/_layout"
      ]
    },
    "/_layout/_protected/community/detail/_layout": {
      "filePath": "_layout/_protected/community/detail/_layout.tsx",
      "parent": "/_layout/_protected/community/detail",
      "children": [
        "/_layout/_protected/community/detail/_layout/$postId"
      ]
    },
    "/_layout/_protected/diary/detail": {
      "filePath": "_layout/_protected/diary/detail",
      "parent": "/_layout/_protected/diary",
      "children": [
        "/_layout/_protected/diary/detail/_layout"
      ]
    },
    "/_layout/_protected/diary/detail/_layout": {
      "filePath": "_layout/_protected/diary/detail/_layout.tsx",
      "parent": "/_layout/_protected/diary/detail",
      "children": [
        "/_layout/_protected/diary/detail/_layout/$cropDiaryId"
      ]
    },
    "/_layout/_protected/diary/growDiary": {
      "filePath": "_layout/_protected/diary/growDiary",
      "parent": "/_layout/_protected/diary",
      "children": [
        "/_layout/_protected/diary/growDiary/_layout"
      ]
    },
    "/_layout/_protected/diary/growDiary/_layout": {
      "filePath": "_layout/_protected/diary/growDiary/_layout.tsx",
      "parent": "/_layout/_protected/diary/growDiary",
      "children": [
        "/_layout/_protected/diary/growDiary/_layout/$cropId"
      ]
    },
    "/_layout/_protected/diary/registerCrop": {
      "filePath": "_layout/_protected/diary/registerCrop",
      "parent": "/_layout/_protected/diary",
      "children": [
        "/_layout/_protected/diary/registerCrop/_layout",
        "/_layout/_protected/diary/registerCrop/"
      ]
    },
    "/_layout/_protected/diary/registerCrop/_layout": {
      "filePath": "_layout/_protected/diary/registerCrop/_layout.tsx",
      "parent": "/_layout/_protected/diary/registerCrop",
      "children": [
        "/_layout/_protected/diary/registerCrop/_layout/1",
        "/_layout/_protected/diary/registerCrop/_layout/2",
        "/_layout/_protected/diary/registerCrop/_layout/3",
        "/_layout/_protected/diary/registerCrop/_layout/4",
        "/_layout/_protected/diary/registerCrop/_layout/5"
      ]
    },
    "/_layout/_protected/diary/write": {
      "filePath": "_layout/_protected/diary/write",
      "parent": "/_layout/_protected/diary",
      "children": [
        "/_layout/_protected/diary/write/_layout",
        "/_layout/_protected/diary/write/"
      ]
    },
    "/_layout/_protected/diary/write/_layout": {
      "filePath": "_layout/_protected/diary/write/_layout.tsx",
      "parent": "/_layout/_protected/diary/write",
      "children": [
        "/_layout/_protected/diary/write/_layout/1",
        "/_layout/_protected/diary/write/_layout/2"
      ]
    },
    "/_layout/_protected/profile/$userId": {
      "filePath": "_layout/_protected/profile/$userId",
      "parent": "/_layout/_protected/profile",
      "children": [
        "/_layout/_protected/profile/$userId/_layout",
        "/_layout/_protected/profile/$userId/cropStorage",
        "/_layout/_protected/profile/$userId/diary"
      ]
    },
    "/_layout/_protected/profile/$userId/_layout": {
      "filePath": "_layout/_protected/profile/$userId/_layout.tsx",
      "parent": "/_layout/_protected/profile/$userId",
      "children": [
        "/_layout/_protected/profile/$userId/_layout/"
      ]
    },
    "/_layout/_protected/profile/changelocation": {
      "filePath": "_layout/_protected/profile/changelocation",
      "parent": "/_layout/_protected/profile",
      "children": [
        "/_layout/_protected/profile/changelocation/_layout"
      ]
    },
    "/_layout/_protected/profile/changelocation/_layout": {
      "filePath": "_layout/_protected/profile/changelocation/_layout.tsx",
      "parent": "/_layout/_protected/profile/changelocation",
      "children": [
        "/_layout/_protected/profile/changelocation/_layout/"
      ]
    },
    "/_layout/_protected/profile/chat": {
      "filePath": "_layout/_protected/profile/chat",
      "parent": "/_layout/_protected/profile",
      "children": [
        "/_layout/_protected/profile/chat/_layout"
      ]
    },
    "/_layout/_protected/profile/chat/_layout": {
      "filePath": "_layout/_protected/profile/chat/_layout.tsx",
      "parent": "/_layout/_protected/profile/chat",
      "children": [
        "/_layout/_protected/profile/chat/_layout/"
      ]
    },
    "/_layout/_protected/profile/picked": {
      "filePath": "_layout/_protected/profile/picked",
      "parent": "/_layout/_protected/profile",
      "children": [
        "/_layout/_protected/profile/picked/_layout"
      ]
    },
    "/_layout/_protected/profile/picked/_layout": {
      "filePath": "_layout/_protected/profile/picked/_layout.tsx",
      "parent": "/_layout/_protected/profile/picked",
      "children": [
        "/_layout/_protected/profile/picked/_layout/"
      ]
    },
    "/_layout/_protected/profile/writed": {
      "filePath": "_layout/_protected/profile/writed",
      "parent": "/_layout/_protected/profile",
      "children": [
        "/_layout/_protected/profile/writed/_layout"
      ]
    },
    "/_layout/_protected/profile/writed/_layout": {
      "filePath": "_layout/_protected/profile/writed/_layout.tsx",
      "parent": "/_layout/_protected/profile/writed",
      "children": [
        "/_layout/_protected/profile/writed/_layout/"
      ]
    },
    "/_layout/_protected/search/$result": {
      "filePath": "_layout/_protected/search/$result",
      "parent": "/_layout/_protected",
      "children": [
        "/_layout/_protected/search/$result/_layout"
      ]
    },
    "/_layout/_protected/search/$result/_layout": {
      "filePath": "_layout/_protected/search/$result/_layout.tsx",
      "parent": "/_layout/_protected/search/$result",
      "children": [
        "/_layout/_protected/search/$result/_layout/"
      ]
    },
    "/_layout/_protected/trade/detail": {
      "filePath": "_layout/_protected/trade/detail",
      "parent": "/_layout/_protected/trade",
      "children": [
        "/_layout/_protected/trade/detail/_layout"
      ]
    },
    "/_layout/_protected/trade/detail/_layout": {
      "filePath": "_layout/_protected/trade/detail/_layout.tsx",
      "parent": "/_layout/_protected/trade/detail",
      "children": [
        "/_layout/_protected/trade/detail/_layout/$tradeId"
      ]
    },
    "/_layout/_protected/trade/from": {
      "filePath": "_layout/_protected/trade/from",
      "parent": "/_layout/_protected/trade",
      "children": [
        "/_layout/_protected/trade/from/_layout"
      ]
    },
    "/_layout/_protected/trade/from/_layout": {
      "filePath": "_layout/_protected/trade/from/_layout.tsx",
      "parent": "/_layout/_protected/trade/from",
      "children": [
        "/_layout/_protected/trade/from/_layout/"
      ]
    },
    "/_layout/_protected/trade/to": {
      "filePath": "_layout/_protected/trade/to",
      "parent": "/_layout/_protected/trade",
      "children": [
        "/_layout/_protected/trade/to/_layout"
      ]
    },
    "/_layout/_protected/trade/to/_layout": {
      "filePath": "_layout/_protected/trade/to/_layout.tsx",
      "parent": "/_layout/_protected/trade/to",
      "children": [
        "/_layout/_protected/trade/to/_layout/"
      ]
    },
    "/_layout/_protected/trade/write": {
      "filePath": "_layout/_protected/trade/write",
      "parent": "/_layout/_protected/trade",
      "children": [
        "/_layout/_protected/trade/write/_layout"
      ]
    },
    "/_layout/_protected/trade/write/_layout": {
      "filePath": "_layout/_protected/trade/write/_layout.tsx",
      "parent": "/_layout/_protected/trade/write",
      "children": [
        "/_layout/_protected/trade/write/_layout/"
      ]
    },
    "/_layout/_protected/community/_layout/": {
      "filePath": "_layout/_protected/community/_layout/index.tsx",
      "parent": "/_layout/_protected/community/_layout"
    },
    "/_layout/_protected/community/create/": {
      "filePath": "_layout/_protected/community/create/index.tsx",
      "parent": "/_layout/_protected/community"
    },
    "/_layout/_protected/diary/_layout/": {
      "filePath": "_layout/_protected/diary/_layout/index.tsx",
      "parent": "/_layout/_protected/diary/_layout"
    },
    "/_layout/_protected/diary/registerCrop/": {
      "filePath": "_layout/_protected/diary/registerCrop/index.tsx",
      "parent": "/_layout/_protected/diary/registerCrop"
    },
    "/_layout/_protected/diary/write/": {
      "filePath": "_layout/_protected/diary/write/index.tsx",
      "parent": "/_layout/_protected/diary/write"
    },
    "/_layout/_protected/profile/_layout/": {
      "filePath": "_layout/_protected/profile/_layout/index.tsx",
      "parent": "/_layout/_protected/profile/_layout"
    },
    "/_layout/_protected/profile/aireport/": {
      "filePath": "_layout/_protected/profile/aireport/index.tsx",
      "parent": "/_layout/_protected/profile"
    },
    "/_layout/_protected/trade/_layout/": {
      "filePath": "_layout/_protected/trade/_layout/index.tsx",
      "parent": "/_layout/_protected/trade/_layout"
    },
    "/_layout/_protected/community/detail/_layout/$postId": {
      "filePath": "_layout/_protected/community/detail/_layout/$postId.tsx",
      "parent": "/_layout/_protected/community/detail/_layout"
    },
    "/_layout/_protected/diary/detail/_layout/$cropDiaryId": {
      "filePath": "_layout/_protected/diary/detail/_layout/$cropDiaryId.tsx",
      "parent": "/_layout/_protected/diary/detail/_layout"
    },
    "/_layout/_protected/diary/growDiary/_layout/$cropId": {
      "filePath": "_layout/_protected/diary/growDiary/_layout/$cropId.tsx",
      "parent": "/_layout/_protected/diary/growDiary/_layout"
    },
    "/_layout/_protected/diary/registerCrop/_layout/1": {
      "filePath": "_layout/_protected/diary/registerCrop/_layout/1.tsx",
      "parent": "/_layout/_protected/diary/registerCrop/_layout"
    },
    "/_layout/_protected/diary/registerCrop/_layout/2": {
      "filePath": "_layout/_protected/diary/registerCrop/_layout/2.tsx",
      "parent": "/_layout/_protected/diary/registerCrop/_layout"
    },
    "/_layout/_protected/diary/registerCrop/_layout/3": {
      "filePath": "_layout/_protected/diary/registerCrop/_layout/3.tsx",
      "parent": "/_layout/_protected/diary/registerCrop/_layout"
    },
    "/_layout/_protected/diary/registerCrop/_layout/4": {
      "filePath": "_layout/_protected/diary/registerCrop/_layout/4.tsx",
      "parent": "/_layout/_protected/diary/registerCrop/_layout"
    },
    "/_layout/_protected/diary/registerCrop/_layout/5": {
      "filePath": "_layout/_protected/diary/registerCrop/_layout/5.tsx",
      "parent": "/_layout/_protected/diary/registerCrop/_layout"
    },
    "/_layout/_protected/diary/write/_layout/1": {
      "filePath": "_layout/_protected/diary/write/_layout/1.tsx",
      "parent": "/_layout/_protected/diary/write/_layout"
    },
    "/_layout/_protected/diary/write/_layout/2": {
      "filePath": "_layout/_protected/diary/write/_layout/2.tsx",
      "parent": "/_layout/_protected/diary/write/_layout"
    },
    "/_layout/_protected/profile/$userId/cropStorage": {
      "filePath": "_layout/_protected/profile/$userId/cropStorage",
      "parent": "/_layout/_protected/profile/$userId",
      "children": [
        "/_layout/_protected/profile/$userId/cropStorage/_layout"
      ]
    },
    "/_layout/_protected/profile/$userId/cropStorage/_layout": {
      "filePath": "_layout/_protected/profile/$userId/cropStorage/_layout.tsx",
      "parent": "/_layout/_protected/profile/$userId/cropStorage",
      "children": [
        "/_layout/_protected/profile/$userId/cropStorage/_layout/"
      ]
    },
    "/_layout/_protected/profile/$userId/diary": {
      "filePath": "_layout/_protected/profile/$userId/diary",
      "parent": "/_layout/_protected/profile/$userId",
      "children": [
        "/_layout/_protected/profile/$userId/diary/_layout"
      ]
    },
    "/_layout/_protected/profile/$userId/diary/_layout": {
      "filePath": "_layout/_protected/profile/$userId/diary/_layout.tsx",
      "parent": "/_layout/_protected/profile/$userId/diary",
      "children": [
        "/_layout/_protected/profile/$userId/diary/_layout/"
      ]
    },
    "/_layout/_protected/profile/aireport/detail/$reportId": {
      "filePath": "_layout/_protected/profile/aireport/detail/$reportId.tsx",
      "parent": "/_layout/_protected/profile"
    },
    "/_layout/_protected/trade/detail/_layout/$tradeId": {
      "filePath": "_layout/_protected/trade/detail/_layout/$tradeId.tsx",
      "parent": "/_layout/_protected/trade/detail/_layout"
    },
    "/_layout/_protected/profile/$userId/_layout/": {
      "filePath": "_layout/_protected/profile/$userId/_layout/index.tsx",
      "parent": "/_layout/_protected/profile/$userId/_layout"
    },
    "/_layout/_protected/profile/changelocation/_layout/": {
      "filePath": "_layout/_protected/profile/changelocation/_layout/index.tsx",
      "parent": "/_layout/_protected/profile/changelocation/_layout"
    },
    "/_layout/_protected/profile/chat/_layout/": {
      "filePath": "_layout/_protected/profile/chat/_layout/index.tsx",
      "parent": "/_layout/_protected/profile/chat/_layout"
    },
    "/_layout/_protected/profile/picked/_layout/": {
      "filePath": "_layout/_protected/profile/picked/_layout/index.tsx",
      "parent": "/_layout/_protected/profile/picked/_layout"
    },
    "/_layout/_protected/profile/writed/_layout/": {
      "filePath": "_layout/_protected/profile/writed/_layout/index.tsx",
      "parent": "/_layout/_protected/profile/writed/_layout"
    },
    "/_layout/_protected/search/$result/_layout/": {
      "filePath": "_layout/_protected/search/$result/_layout/index.tsx",
      "parent": "/_layout/_protected/search/$result/_layout"
    },
    "/_layout/_protected/trade/from/_layout/": {
      "filePath": "_layout/_protected/trade/from/_layout/index.tsx",
      "parent": "/_layout/_protected/trade/from/_layout"
    },
    "/_layout/_protected/trade/to/_layout/": {
      "filePath": "_layout/_protected/trade/to/_layout/index.tsx",
      "parent": "/_layout/_protected/trade/to/_layout"
    },
    "/_layout/_protected/trade/write/_layout/": {
      "filePath": "_layout/_protected/trade/write/_layout/index.tsx",
      "parent": "/_layout/_protected/trade/write/_layout"
    },
    "/_layout/_protected/profile/$userId/cropStorage/_layout/": {
      "filePath": "_layout/_protected/profile/$userId/cropStorage/_layout/index.tsx",
      "parent": "/_layout/_protected/profile/$userId/cropStorage/_layout"
    },
    "/_layout/_protected/profile/$userId/diary/_layout/": {
      "filePath": "_layout/_protected/profile/$userId/diary/_layout/index.tsx",
      "parent": "/_layout/_protected/profile/$userId/diary/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
